import React, { createContext, useContext, ReactNode } from 'react';

export type Language = 'vi' | 'en' | 'fr' | 'ja' | 'ko' | 'zh' | 'de' | 'es';

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' }
];

export const translations = {
  "vi": {
    "selectLanguage": "Chọn Ngôn Ngữ",
    "topBarAnnouncement": "Chiến dịch Ngày Hội Dọn Rác Toàn Cầu 2026 đang mở đăng ký tình nguyện viên trên toàn quốc!",
    "topBarTagline": "Let's do it! Vietnam - Chung tay vì một Việt Nam xanh - sạch - không rác thải!",
    "navWhoWeAre": "Chúng Tôi Là Ai",
    "navWhatWeDo": "Chúng Tôi Làm Gì",
    "navOurTeam": "Đội Ngũ",
    "navOurPartners": "Đối Tác",
    "navProject": "Dự Án",
    "navOther": "Khác",
    "navMediaOnUs": "Báo Chí & Truyền Thông",
    "navNews": "Tin Tức",
    "navVideos": "Video",
    "videosPageBadge": "HÀNH ĐỘNG VÌ MÔI TRƯỜNG",
    "videosPageTitle": "Thước Phim & Phóng Sự Hành Động",
    "videosPageSubtitle": "Theo dõi các phóng sự truyền hình, thước phim tài liệu và câu chuyện truyền cảm hứng từ các chiến dịch dọn rác Let's do it! Vietnam.",
    "videosPageCountSuffix": "Video phóng sự",
    "videosPageAddBtn": "Thêm Video Mới",
    "videosPageEmptyTitle": "Chưa có video nào",
    "videosPageEmptyDesc": "Dán link YouTube để chia sẻ video phóng sự",
    "navContactUs": "Liên Hệ",
    "navMap": "Bản Đồ",
    "projectWcd": "Ngày Hội Dọn Rác Toàn Cầu",
    "projectEnvDay": "Ngày Môi Trường Thế Giới",
    "projectGreenOcean": "Chiến Dịch Đại Dương Xanh",
    "projectYoungWildlife": "Bảo Tồn Động Vật Hoang Dã",
    "projectWorkshop": "Hội Thảo Sinh Thái Cộng Đồng",
    "viewAllProjects": "Xem tất cả các chiến dịch »",
    "adminDb": "Quản trị CSDL",
    "register": "Đăng Ký",
    "login": "Đăng Nhập",
    "joinVolunteer": "Đăng Ký TNV",
    "profile": "Hồ sơ cá nhân",
    "logout": "Đăng xuất",
    "signUpSignIn": "Đăng Nhập",
    "roleAdmin": "Quản Trị Viên",
    "roleVolunteer": "Tình Nguyện Viên",
    "close": "Đóng",
    "privacyPolicy": "Chính sách bảo mật",
    "termsOfService": "Điều khoản tình nguyện",
    "contactBubbleTitle": "Hỗ Trợ & Liên Hệ",
    "contactBubbleSubtitle": "Let's do it! Vietnam sẵn sàng giải đáp",
    "contactBubbleOpenBtn": "Mở Trang Gửi Lời Nhắn",
    "heroSlide1Badge": "NGÀY HỘI DỌN RÁC THẾ GIỚI 2026 • HÀNH TRÌNH 10 NĂM VÌ MÔI TRƯỜNG",
    "heroSlide1Title": "NGÀY HỘI DỌN RÁC THẾ GIỚI",
    "heroSlide1Desc": "Hơn 5.000 bạn trẻ, gia đình và tổ chức cùng hòa chung nhịp đập vì một Việt Nam xanh - sạch - không rác thải.",
    "registerNowBtn": "Đăng ký tham gia ngay",
    "exploreCampaignsBtn": "Xem các chiến dịch",
    "heroSlideTab1": "Banner Đại Hội",
    "heroSlideTab2": "Thông Điệp Toàn Cầu",
    "heroSlide2Badge": "Chiến Dịch Toàn Cầu",
    "heroSlide2Title1": "Ngày Hội Dọn Rác:",
    "heroSlide2Title2": "Hành Động Địa Phương,\nTác Động Toàn Cầu",
    "heroSlide2Desc": "Huy động hàng nghìn tình nguyện viên nhiệt huyết bảo vệ môi trường, phân loại rác thải và nâng cao ý thức cộng đồng.",
    "featureProvinces": "63 Tỉnh thành tham gia",
    "featureCert": "Cấp chứng nhận tình nguyện",
    "featureGear": "Trang bị bảo hộ miễn phí",
    "joinNextEvent": "Tham gia sự kiện tiếp theo",
    "exploreMap": "Bản Đồ Điểm Dọn",
    "aboutBadge": "Về Sáng Kiến Môi Trường",
    "aboutTitle": "Phong Trào Let's do it! Vietnam",
    "aboutP1": "Ngày Hội Dọn Rác Toàn Cầu là phong trào hành động công dân vì môi trường lớn nhất thế giới, quy tụ hàng triệu tình nguyện viên tại hơn 190 quốc gia.",
    "aboutP2": "Từ năm 2015, chúng tôi không chỉ thu gom rác mà còn nâng cao nhận thức, số hóa các điểm ô nhiễm và xây dựng thói quen sống không rác thải.",
    "statTons": "Tấn Rác Đã Thu Gom",
    "statTonsSub": "Được thu gom và phân loại an toàn",
    "statVolunteers": "Tình Nguyện Viên Tham Gia",
    "statVolunteersSub": "Trên khắp 63 tỉnh thành Việt Nam",
    "statEvents": "Chiến Dịch Đã Tổ Chức",
    "statEventsSub": "Đồng loạt ra quân trên toàn quốc",
    "whoWeAreBadge": "Hành trình 10 năm kết nối cộng đồng",
    "whoWeAreTitlePrefix": "Chúng Tôi Là",
    "whoWeAreIntro": "Thành lập từ năm 2015, Let's do it! Vietnam là tổ chức phi lợi nhuận trực thuộc mạng lưới toàn cầu Let's Do It World (có trụ sở tại Estonia), với sứ mệnh nâng cao nhận thức cộng đồng và kêu gọi hành động vì một Việt Nam xanh, sạch, không rác thải.",
    "whoWeAreMissionTitle": "Sứ Mệnh",
    "whoWeAreMissionDesc": "Kết nối và trao quyền cho hàng triệu người dân Việt Nam, đặc biệt là thế hệ trẻ, thông qua các chiến dịch dọn rác quy mô toàn quốc, ứng dụng công nghệ bản đồ số hóa điểm nóng ô nhiễm và thúc đẩy văn hóa tiêu dùng bền vững.",
    "whoWeAreVisionTitle": "Tầm Nhìn 2030",
    "whoWeAreVisionDesc": "Trở thành phong trào công dân vì môi trường lớn nhất tại Việt Nam, đưa 100% các điểm đen rác thải đô thị và bờ biển vào mạng lưới kiểm soát - phân loại tuần hoàn, đồng thời là đối tác chiến lược của Liên Hợp Quốc (UNEP).",
    "whoWeAreValuesTitle": "Giá Trị Cốt Lõi Của Chúng Tôi",
    "whoWeAreVal1Title": "Hành Động Tích Cực",
    "whoWeAreVal1Desc": "Chúng tôi không chỉ lên tiếng mà cùng nhau xắn tay áo dọn dẹp, biến sự trăn trở thành kết quả thực tế đo đếm được.",
    "whoWeAreVal2Title": "Đoàn Kết & Hòa Nhập",
    "whoWeAreVal2Desc": "Mọi cá nhân, bất kể độ tuổi, ngành nghề hay hoàn cảnh, đều có thể đóng góp một phần công sức cho thiên nhiên.",
    "whoWeAreVal3Title": "Minh Bạch & Dữ Liệu",
    "whoWeAreVal3Desc": "Hệ thống cơ sở dữ liệu số hóa theo dõi chính xác từng kg rác thu gom, từng khoản tài trợ và chứng nhận tình nguyện.",
    "whoWeAreCtaTitle": "Bạn Đã Sẵn Sàng Tạo Nên Sự Khác Biệt?",
    "whoWeAreCtaDesc": "Hãy cùng hàng nghìn tình nguyện viên khác ghi tên mình vào chiến dịch World Cleanup Day 2026 ngay hôm nay.",
    "whatWeDoBadge": "4 Trụ Cột Hành Động",
    "whatWeDoTitle": "Chúng Tôi Làm Gì?",
    "whatWeDoIntro": "Từ việc nhặt từng mẩu rác trên bãi biển đến việc áp dụng cơ sở dữ liệu số hóa rác thải đại dương, Let's do it! Vietnam xây dựng giải pháp toàn diện và bền vững.",
    "whatWeDoPillar1Title": "Chiến Dịch Dọn Rác Toàn Quốc",
    "whatWeDoPillar1Desc": "Quy tụ hàng chục nghìn tình nguyện viên đồng loạt ra quân vào Ngày Hội Dọn Rác Thế Giới (WCD), làm sạch bờ biển, công viên, rừng nguyên sinh và các khu dân cư.",
    "whatWeDoPillar2Title": "Giáo Dục Sinh Thái & Hội Thảo",
    "whatWeDoPillar2Desc": "Đào tạo kỹ năng phân loại rác tại nguồn, làm gạch sinh thái (ecobricks), ủ phân hữu cơ và lối sống không rác thải (Zero Waste) cho học sinh, sinh viên.",
    "whatWeDoPillar3Title": "Bản Đồ Số Hóa Điểm Nóng Rác Thải",
    "whatWeDoPillar3Desc": "Áp dụng công nghệ định vị GPS và cơ sở dữ liệu số để cộng đồng báo cáo bãi rác tự phát, theo dõi tiến độ dọn dẹp và phân tích loại hình rác thải.",
    "whatWeDoPillar4Title": "Kinh Tế Tuần Hoàn & Đối Tác ESG",
    "whatWeDoPillar4Desc": "Kết nối các nhà máy tái chế bao bì, hỗ trợ doanh nghiệp thực hiện trách nhiệm mở rộng của nhà sản xuất (EPR) và giảm thiểu đồ nhựa một lần.",
    "whatWeDoExploreProjectsBtn": "Khám Phá Các Dự Án",
    "ourTeamBadge": "Ban Điều Hành & Điều Phối Viên",
    "ourTeamTitle": "Đội Ngũ Let's do it! Vietnam",
    "ourTeamDesc": "Những con người đầy tâm huyết, năng động và kiên trì dẫn dắt các chiến dịch môi trường trên khắp các tỉnh thành cả nước.",
    "ourTeamJoinTitle": "Bạn Muốn Trở Thành Điều Phối Viên Vùng?",
    "ourTeamJoinDesc": "Chúng tôi luôn tìm kiếm những bạn trẻ nhiệt huyết phụ trách các điểm cầu tại các tỉnh thành mới. Hãy tham gia đợt tuyển dụng Core Team 2026/2026 ngay hôm nay!",
    "ourTeamJoinBtn": "Gửi Hồ Sơ Ứng Tuyển Core Team",
    "ourPartnersBadge": "Mạng Lưới Đối Tác & Tài Trợ",
    "ourPartnersTitle": "Đối Tác & Nhà Tài Trợ",
    "ourPartnersDesc": "Let's do it! Vietnam tự hào nhận được sự đồng hành, bảo trợ và tài trợ từ các cơ quan chính phủ, tổ chức quốc tế, trường đại học và các tập đoàn tiên phong trong chuyển đổi xanh.",
    "becomePartnerBtn": "Đăng Ký Trở Thành Đối Tác",
    "getInvolvedTitle": "Cùng Chung Tay Hành Động",
    "getInvolvedSubtitle": "Mỗi hành động của bạn, dù là tham gia dọn rác, đồng hành doanh nghiệp hay ủng hộ kinh phí, đều tạo nên sự thay đổi to lớn.",
    "cardVolTitle": "Đăng Ký Làm Tình Nguyện Viên",
    "cardVolDesc": "Tham gia các điểm dọn rác gần bạn, nhận áo đồng phục, dụng cụ bảo hộ và chứng nhận tình nguyện viên toàn cầu.",
    "cardVolBtn": "Đăng Ký Tình Nguyện",
    "cardPartnerTitle": "Đồng Hành Doanh Nghiệp & Đối Tác",
    "cardPartnerDesc": "Hợp tác trách nhiệm xã hội doanh nghiệp (ESG/CSR), tổ chức ngày hội dọn rác nội bộ và tài trợ hoạt động.",
    "cardPartnerBtn": "Trở Thành Đối Tác",
    "galleryBadge": "Khoảnh Khắc Hành Động",
    "galleryTitle": "Thư Viện Hình Ảnh & Phóng Sự",
    "gallerySubtitle": "Những nụ cười, giọt mồ hôi và khoảnh khắc chuyển mình của các bãi rác qua từng mùa chiến dịch.",
    "galleryViewAll": "Xem Tất Cả Ảnh",
    "mapTitle": "Bản Đồ Điểm Dọn Rác Toàn Quốc",
    "mapSubtitle": "Nhấp chuột vào bất kỳ vị trí nào trên bản đồ để ghim địa chỉ và đăng tải điểm rác mới cần dọn dẹp.",
    "streets": "Đường phố",
    "satellite": "Vệ tinh",
    "terrain": "Địa hình",
    "allProvinces": "Toàn quốc",
    "cleanupSpots": "Điểm Dọn Rác",
    "pinNewLocation": "Đã Ghim Địa Điểm Mới",
    "postTrashSpotHere": "Đăng Bài & Ảnh Điểm Rác Tại Đây",
    "viewDetails": "Xem Chi Tiết",
    "registerNow": "Đăng Ký Ngay",
    "footerDesc": "Mạng lưới hành động vì môi trường toàn cầu kết nối cộng đồng vì một Việt Nam xanh, sạch, bền vững.",
    "quickLinks": "Liên Kết Nhanh",
    "contactInfo": "Thông Tin Liên Hệ",
    "followUs": "Theo Dõi Chúng Tôi",
    "allRightsReserved": "Bản quyền thuộc về Let's do it! Vietnam. Tất cả các quyền được bảo lưu.",
    "newsPageBadge": "Tin Tức & Truyền Thông Báo Chí",
    "newsPageTitleMedia": "Báo Chí & Truyền Hình Về Chúng Tôi",
    "newsPageTitleDefault": "Tin Tức & Hoạt Động Môi Trường",
    "newsPageSubtitle": "Cập nhật các bản tin thời sự, phóng sự VTV, bài viết phân tích và câu chuyện truyền cảm hứng từ các chiến dịch dọn rác thực tế.",
    "newsPageAddArticleBtn": "Đăng Bài Viết / Tin Tức Mới",
    "newsPageAllCategoriesLabel": "Tất cả bài viết",
    "newsPagePendingBadge": "Chờ Duyệt (Pending)",
    "newsPageSourceLabel": "Nguồn:",
    "newsPageReadMoreBtn": "Đọc bài viết",
    "newsPageBackToListBtn": "Quay lại danh sách",
    "newsPageSourceOriginalLabel": "Xem bài gốc trên trang báo:",
    "newsPageDefaultSourceLabel": "Trang báo gốc",
    "newsCatAll": "Tất cả bài viết",
    "newsCatNews": "Tin Tức",
    "newsCatMedia": "Báo Chí & Truyền Hình",
    "newsCatPress": "Thông Cáo Báo Chí",
    "newsCatImpact": "Câu Chuyện Lan Tỏa",
    "projectsBadge": "Hành Động Vì Môi Trường",
    "projectsTitle": "Các Chiến Dịch & Dự Án Môi Trường Trọng Điểm",
    "projectsSubtitle": "Chọn chiến dịch tại địa phương của bạn và chung tay cùng hàng nghìn tình nguyện viên hành động ngay hôm nay.",
    "projectsAddBtn": "Đăng Ký Tạo Chiến Dịch Dọn Rác",
    "projectsAllCategoryLabel": "Tất Cả Chiến Dịch",
    "projectsDetailBtn": "Xem Chi Tiết Chiến Dịch",
    "projectsJoinBtn": "Đăng Ký Tham Gia",
    "fullGalleryBadge": "Kho Tư Liệu Hình Ảnh & Phóng Sự",
    "fullGalleryTitle": "Thư Viện Ảnh & Phim Tư Liệu",
    "fullGallerySubtitle": "Những nụ cười, giọt mồ hôi và khoảnh khắc đổi thay của các bãi rác qua từng mùa chiến dịch Let's do it! Vietnam.",
    "fullGalleryAllYearsLabel": "Tất cả các năm",
    "fullGalleryYearPrefix": "Năm",
    "fullGalleryUploadBtn": "Tải Ảnh Mới Lên",
    "contactPageBadge": "Kết Nối Trực Tiếp",
    "contactPageSubtitle": "Bạn có câu hỏi, muốn phản ánh một bãi rác tự phát, hoặc mong muốn hợp tác chiến dịch tại địa phương? Hãy gửi thông tin cho chúng tôi.",
    "contactPageFindUsTitle": "Bạn có thể tìm thấy chúng tôi tại",
    "contactPageEmailLabel": "ĐỊA CHỈ EMAIL",
    "contactPagePhoneLabel1": "SỐ ĐIỆN THOẠI",
    "contactPagePhoneLabel2": "SỐ ĐIỆN THOẠI",
    "contactPhone1Default": "035.872.6755 (Anh Sơn)",
    "contactPhone2Default": "0968.514.882 (Chị Tú)",
    "contactSubjectOpt1": "Đăng ký tình nguyện viên & Tham gia chiến dịch",
    "contactSubjectOpt2": "Hợp tác doanh nghiệp & Tài trợ ESG",
    "contactSubjectOpt3": "Báo cáo điểm đen rác thải ô nhiễm",
    "contactSubjectOpt4": "Hỏi đáp chung & Báo chí",
    "contactPageFormTitle": "Gửi Tin Nhắn Cho Ban Điều Phối",
    "contactPageThankYouTitle": "Cảm Ơn Bạn Đã Liên Hệ!",
    "contactPageThankYouMsgPrefix": "Tin nhắn của bạn đã được ghi nhận. Ban điều phối sẽ phản hồi qua email ",
    "contactPageThankYouMsgSuffix": " sớm nhất.",
    "contactPageSendAnotherBtn": "Gửi tin nhắn khác",
    "contactPageNameLabel": "Họ và Tên *",
    "contactPageEmailFieldLabel": "Địa chỉ Email *",
    "contactPagePhoneFieldLabel": "Số điện thoại (Đúng 10 số)",
    "contactPageSubjectLabel": "Chủ đề",
    "contactPageMessageLabel": "Nội dung tin nhắn *",
    "contactPageSubmitBtn": "Gửi Tin Nhắn Ngay"
  },
  "en": {
    "selectLanguage": "Select Language",
    "topBarAnnouncement": "World Cleanup Day 2026 is now accepting nationwide volunteer registrations!",
    "topBarTagline": "Let's do it! Vietnam - Join hands for a green, clean, zero-waste Vietnam!",
    "navWhoWeAre": "Who We Are",
    "navWhatWeDo": "What We Do",
    "navOurTeam": "Our Team",
    "navOurPartners": "Our Partners",
    "navProject": "Projects",
    "navOther": "Other",
    "navMediaOnUs": "Media On Us",
    "navNews": "News",
    "navVideos": "Videos",
    "videosPageBadge": "TAKE ACTION",
    "videosPageTitle": "Capturing Change, One Frame at a Time",
    "videosPageSubtitle": "Watch TV reports, documentaries, and inspiring stories from Let's do it! Vietnam cleanup campaigns.",
    "videosPageCountSuffix": "Videos",
    "videosPageAddBtn": "Add New Video",
    "videosPageEmptyTitle": "No videos yet",
    "videosPageEmptyDesc": "Paste a YouTube link to share a media video",
    "navContactUs": "Contact Us",
    "navMap": "Cleanup Map",
    "projectWcd": "World Cleanup Day",
    "projectEnvDay": "Environmental Day",
    "projectGreenOcean": "Green Ocean Campaign",
    "projectYoungWildlife": "Young Conservationists Save The Wildlife",
    "projectWorkshop": "Community Workshop",
    "viewAllProjects": "View all campaigns »",
    "adminDb": "Database Admin",
    "register": "Register",
    "login": "Login",
    "joinVolunteer": "Volunteer",
    "profile": "My Profile",
    "logout": "Logout",
    "signUpSignIn": "Sign In",
    "roleAdmin": "Administrator",
    "roleVolunteer": "Volunteer",
    "close": "Close",
    "privacyPolicy": "Privacy Policy",
    "termsOfService": "Terms of Service",
    "contactBubbleTitle": "Quick Support",
    "contactBubbleSubtitle": "We are here to help",
    "contactBubbleOpenBtn": "Open Contact Page",
    "heroSlide1Badge": "WORLD CLEANUP DAY 2026 • 10-YEAR JOURNEY FOR THE ENVIRONMENT",
    "heroSlide1Title": "WORLD CLEANUP DAY",
    "heroSlide1Desc": "Over 5,000 youth, families, and organizations united for a green, clean, and zero-waste Vietnam.",
    "registerNowBtn": "Register to Join Now",
    "exploreCampaignsBtn": "Explore Campaigns",
    "heroSlideTab1": "Main Banner",
    "heroSlideTab2": "Global Message",
    "heroSlide2Badge": "Global Campaign",
    "heroSlide2Title1": "World Cleanup Day:",
    "heroSlide2Title2": "Global Impact, Local Action",
    "heroSlide2Desc": "Mobilizing thousands of passionate volunteers across Vietnam in environmental protection, trash sorting, and community pride.",
    "featureProvinces": "63 Provinces Participating",
    "featureCert": "Volunteer Certificate Issued",
    "featureGear": "Free Safety Gear Provided",
    "joinNextEvent": "Join the Next Event",
    "exploreMap": "Explore Cleanup Map",
    "aboutBadge": "About the Initiative",
    "aboutTitle": "Let's do it! Vietnam Movement",
    "aboutP1": "World Cleanup Day is the world's largest civic environmental movement, mobilizing millions of volunteers across 190+ countries.",
    "aboutP2": "Since 2015, we not only collect waste but transform community awareness, map pollution hotspots, and build zero-waste habits.",
    "statTons": "Tons Trash Collected",
    "statTonsSub": "Safely collected and sorted",
    "statVolunteers": "Volunteers Engaged",
    "statVolunteersSub": "Across 63 provinces in Vietnam",
    "statEvents": "Cleanup Events Organized",
    "statEventsSub": "Mobilized nationwide",
    "whoWeAreBadge": "10-Year Community Journey",
    "whoWeAreTitlePrefix": "We Are",
    "whoWeAreIntro": "Founded in 2015, Let's do it! Vietnam is a non-profit organization affiliated with the global network Let's Do It World (headquartered in Estonia), with the mission to raise community awareness and call for action towards a green, clean, and zero-waste Vietnam.",
    "whoWeAreMissionTitle": "Our Mission",
    "whoWeAreMissionDesc": "Connecting and empowering millions of Vietnamese citizens, especially the youth, through nationwide cleanup campaigns, digital hotspot mapping technologies, and sustainable consumption advocacy.",
    "whoWeAreVisionTitle": "Vision 2030",
    "whoWeAreVisionDesc": "To become the largest civic environmental movement in Vietnam, bringing 100% of urban and coastal waste hotspots into a circular management network while serving as a strategic partner of UNEP.",
    "whoWeAreValuesTitle": "Our Core Values",
    "whoWeAreVal1Title": "Positive Action",
    "whoWeAreVal1Desc": "We don't just raise awareness; we roll up our sleeves and clean up together, turning environmental concern into measurable impact.",
    "whoWeAreVal2Title": "Unity & Inclusivity",
    "whoWeAreVal2Desc": "Every individual, regardless of age, background, or profession, can contribute meaningfully to nature.",
    "whoWeAreVal3Title": "Transparency & Data-Driven",
    "whoWeAreVal3Desc": "Digital database tracking precisely every kilogram of waste collected, every grant received, and verified volunteer certificates.",
    "whoWeAreCtaTitle": "Ready to Make a Difference?",
    "whoWeAreCtaDesc": "Join thousands of passionate volunteers and register for World Cleanup Day 2026 today.",
    "whatWeDoBadge": "4 Core Action Pillars",
    "whatWeDoTitle": "What We Do",
    "whatWeDoIntro": "From picking up litter on local beaches to digitalizing ocean waste data, Let's do it! Vietnam builds comprehensive and sustainable environmental solutions.",
    "whatWeDoPillar1Title": "Nationwide Cleanup Campaigns",
    "whatWeDoPillar1Desc": "Mobilizing tens of thousands of volunteers simultaneously on World Cleanup Day (WCD) to clean beaches, parks, forests, and neighborhoods.",
    "whatWeDoPillar2Title": "Eco-Education & Workshops",
    "whatWeDoPillar2Desc": "Training waste segregation at source, making ecobricks, composting, and promoting Zero Waste lifestyles for students and communities.",
    "whatWeDoPillar3Title": "Digital Trash Hotspot Mapping",
    "whatWeDoPillar3Desc": "Leveraging GPS and digital databases for citizen reporting of illegal dump sites, tracking cleanup milestones, and waste analytics.",
    "whatWeDoPillar4Title": "Circular Economy & ESG Partners",
    "whatWeDoPillar4Desc": "Connecting packaging recyclers, supporting businesses in Extended Producer Responsibility (EPR), and eliminating single-use plastics.",
    "whatWeDoExploreProjectsBtn": "Explore Our Projects",
    "ourTeamBadge": "Leadership & Coordinators",
    "ourTeamTitle": "The Let's do it! Vietnam Team",
    "ourTeamDesc": "Passionate, energetic, and dedicated leaders driving environmental initiatives across Vietnam.",
    "ourTeamJoinTitle": "Want to Become a Regional Coordinator?",
    "ourTeamJoinDesc": "We're always looking for passionate young people to lead our chapters in new provinces. Join the Core Team 2026/2026 recruitment drive today!",
    "ourTeamJoinBtn": "Apply to the Core Team",
    "ourPartnersBadge": "Partner & Sponsor Network",
    "ourPartnersTitle": "Our Partners & Sponsors",
    "ourPartnersDesc": "Let's do it! Vietnam is proud to be accompanied and supported by government agencies, international organizations, universities, and visionary enterprises.",
    "becomePartnerBtn": "Become a Partner",
    "getInvolvedTitle": "Get Involved Today",
    "getInvolvedSubtitle": "Every action you take creates meaningful change for the environment.",
    "cardVolTitle": "Register to Volunteer",
    "cardVolDesc": "Join cleanup spots near you, receive volunteer shirts, safety gear, and official global certificates.",
    "cardVolBtn": "Register to Volunteer",
    "cardPartnerTitle": "Corporate & Partner Engagement",
    "cardPartnerDesc": "Collaborate through CSR/ESG partnerships, internal cleanup days, and organizational sponsorship.",
    "cardPartnerBtn": "Become a Partner",
    "galleryBadge": "Moments of Action",
    "galleryTitle": "Photo & Media Gallery",
    "gallerySubtitle": "Smiles, dedication, and transformative progress across our cleanup seasons.",
    "galleryViewAll": "View Full Gallery",
    "mapTitle": "Nationwide Cleanup Spot Map",
    "mapSubtitle": "Click anywhere on the map to pin a location and report a new trash cleanup spot for admin review.",
    "streets": "Streets",
    "satellite": "Satellite",
    "terrain": "Terrain",
    "allProvinces": "All Vietnam",
    "cleanupSpots": "Cleanup Spots",
    "pinNewLocation": "New Location Pinned",
    "postTrashSpotHere": "Submit Trash Spot & Photo Here",
    "viewDetails": "View Details",
    "registerNow": "Register Now",
    "footerDesc": "Global civic environmental movement connecting communities for a green, clean, and sustainable Vietnam.",
    "quickLinks": "Quick Links",
    "contactInfo": "Contact Information",
    "followUs": "Follow Us",
    "allRightsReserved": "Copyright © Let's do it! Vietnam. All rights reserved.",
    "newsPageBadge": "News & Media Coverage",
    "newsPageTitleMedia": "Press & TV Coverage About Us",
    "newsPageTitleDefault": "News & Environmental Activities",
    "newsPageSubtitle": "Stay updated with the latest news, VTV features, in-depth articles, and inspiring stories from our real-world cleanup campaigns.",
    "newsPageAddArticleBtn": "Submit an Article / News",
    "newsPageAllCategoriesLabel": "All Articles",
    "newsPagePendingBadge": "Pending Review",
    "newsPageSourceLabel": "Source:",
    "newsPageReadMoreBtn": "Read Article",
    "newsPageBackToListBtn": "Back to List",
    "newsPageSourceOriginalLabel": "View original article at:",
    "newsPageDefaultSourceLabel": "Original Source",
    "newsCatAll": "All Articles",
    "newsCatNews": "News",
    "newsCatMedia": "Media On Us",
    "newsCatPress": "Press Release",
    "newsCatImpact": "Impact Story",
    "projectsBadge": "Environmental Action",
    "projectsTitle": "Flagship Environmental Campaigns & Projects",
    "projectsSubtitle": "Select a campaign in your locality and join thousands of volunteers in taking action today.",
    "projectsAddBtn": "Register a New Cleanup Campaign",
    "projectsAllCategoryLabel": "All Campaigns",
    "projectsDetailBtn": "View Campaign Details",
    "projectsJoinBtn": "Register to Participate",
    "fullGalleryBadge": "Photo & Video Archive",
    "fullGalleryTitle": "Documentary & Photo Gallery",
    "fullGallerySubtitle": "Smiles, sweat, and the transformation of cleanup sites through each Let's do it! Vietnam campaign season.",
    "fullGalleryAllYearsLabel": "All Years",
    "fullGalleryYearPrefix": "Year",
    "fullGalleryUploadBtn": "Upload New Photo",
    "contactPageBadge": "Get In Touch",
    "contactPageSubtitle": "Have a question, want to report a waste hotspot, or interested in a local campaign partnership? Send us your details.",
    "contactPageFindUsTitle": "You can find us at",
    "contactPageEmailLabel": "EMAIL ADDRESS",
    "contactPagePhoneLabel1": "PHONE NUMBER",
    "contactPagePhoneLabel2": "PHONE NUMBER",
    "contactPhone1Default": "035.872.6755 (Mr. Son)",
    "contactPhone2Default": "0968.514.882 (Ms. Tu)",
    "contactSubjectOpt1": "Volunteer Registration & Campaign Participation",
    "contactSubjectOpt2": "Corporate Partnership & ESG Sponsorship",
    "contactSubjectOpt3": "Report Illegal Trash Hotspot",
    "contactSubjectOpt4": "General Inquiries & Media",
    "contactPageFormTitle": "Send a Message to Our Team",
    "contactPageThankYouTitle": "Thank You for Reaching Out!",
    "contactPageThankYouMsgPrefix": "Your message has been received. Our team will reply via email ",
    "contactPageThankYouMsgSuffix": " as soon as possible.",
    "contactPageSendAnotherBtn": "Send Another Message",
    "contactPageNameLabel": "Full Name *",
    "contactPageEmailFieldLabel": "Email Address *",
    "contactPagePhoneFieldLabel": "Phone Number (10 digits)",
    "contactPageSubjectLabel": "Subject",
    "contactPageMessageLabel": "Message *",
    "contactPageSubmitBtn": "Send Message"
  },
  "fr": {
    "selectLanguage": "Choisir la langue",
    "topBarAnnouncement": "La Journée mondiale du nettoyage 2026 ouvre les inscriptions des bénévoles !",
    "topBarTagline": "Let's do it! Vietnam - Unissons-nous pour un Vietnam vert, propre et sans déchets !",
    "navWhoWeAre": "Qui sommes-nous",
    "navWhatWeDo": "Ce que nous faisons",
    "navOurTeam": "Notre équipe",
    "navOurPartners": "Nos partenaires",
    "navProject": "Projets",
    "navOther": "Autre",
    "navMediaOnUs": "Médias sur nous",
    "navNews": "Actualités",
    "navVideos": "Vidéos",
    "videosPageBadge": "PASSER À L’ACTION",
    "videosPageTitle": "Capturer le changement, image par image",
    "videosPageSubtitle": "Regardez les reportages télévisés et les documentaires de nos campagnes de nettoyage.",
    "videosPageCountSuffix": "Vidéos",
    "videosPageAddBtn": "Ajouter une vidéo",
    "videosPageEmptyTitle": "Aucune vidéo pour le moment",
    "videosPageEmptyDesc": "Collez un lien YouTube pour partager une vidéo",
    "navContactUs": "Contactez-nous",
    "navMap": "Carte de nettoyage",
    "projectWcd": "Journée mondiale du nettoyage",
    "projectEnvDay": "Journée de l'environnement",
    "projectGreenOcean": "Campagne Océan Vert",
    "projectYoungWildlife": "Jeunes écologistes pour la faune",
    "projectWorkshop": "Atelier communautaire",
    "viewAllProjects": "Voir tous les projets »",
    "adminDb": "Admin BDD",
    "register": "S'inscrire",
    "login": "Connexion",
    "joinVolunteer": "Bénévolat",
    "profile": "Mon profil",
    "logout": "Déconnexion",
    "signUpSignIn": "Connexion",
    "roleAdmin": "Administrateur",
    "roleVolunteer": "Bénévole",
    "close": "Fermer",
    "privacyPolicy": "Politique de confidentialité",
    "termsOfService": "Conditions d'utilisation",
    "contactBubbleTitle": "Assistance rapide",
    "contactBubbleSubtitle": "Let's do it! Vietnam est là pour vous aider",
    "contactBubbleOpenBtn": "Ouvrir la page de contact",
    "heroSlide1Badge": "JOURNÉE MONDIALE DU NETTOYAGE 2026 • 10 ANS D'ACTION",
    "heroSlide1Title": "JOURNÉE MONDIALE DU NETTOYAGE",
    "heroSlide1Desc": "Plus de 5 000 jeunes, familles et organisations unis pour un Vietnam vert, propre et sans déchets.",
    "registerNowBtn": "S'inscrire maintenant",
    "exploreCampaignsBtn": "Explorer les campagnes",
    "heroSlideTab1": "Bannière principale",
    "heroSlideTab2": "Message mondial",
    "heroSlide2Badge": "Campagne mondiale",
    "heroSlide2Title1": "Journée mondiale du nettoyage :",
    "heroSlide2Title2": "Impact mondial, action locale",
    "heroSlide2Desc": "Mobilisation de milliers de bénévoles passionnés pour la protection de l'environnement au Vietnam.",
    "featureProvinces": "63 provinces participantes",
    "featureCert": "Certificat officiel délivré",
    "featureGear": "Équipement de sécurité fourni",
    "joinNextEvent": "Participer au prochain événement",
    "exploreMap": "Voir la carte",
    "aboutBadge": "À propos de l'initiative",
    "aboutTitle": "Mouvement Let's do it! Vietnam",
    "aboutP1": "Le plus grand mouvement civique mondial pour l'environnement réunissant des millions de bénévoles dans plus de 190 pays.",
    "aboutP2": "Depuis 2015, nous transformons les consciences et créons des habitudes zéro déchet durables.",
    "statTons": "Tonnes de déchets collectées",
    "statTonsSub": "Collectées et triées en toute sécurité",
    "statVolunteers": "Bénévoles mobilisés",
    "statVolunteersSub": "Dans 63 provinces du Vietnam",
    "statEvents": "Campagnes organisées",
    "statEventsSub": "Déployées à l'échelle nationale",
    "whoWeAreBadge": "10 ans d'engagement communautaire",
    "whoWeAreTitlePrefix": "Nous Sommes",
    "whoWeAreIntro": "Fondée en 2015, Let's do it! Vietnam est une organisation à but non lucratif affiliée au réseau mondial Let's Do It World, avec pour mission d'agir pour un Vietnam sans déchets.",
    "whoWeAreMissionTitle": "Notre Mission",
    "whoWeAreMissionDesc": "Sensibiliser et mobiliser des millions de citoyens vietnamiens par des campagnes de nettoyage d'envergure nationale et des outils cartographiques participatifs.",
    "whoWeAreVisionTitle": "Vision 2030",
    "whoWeAreVisionDesc": "Devenir le plus grand mouvement citoyen pour l'écologie au Vietnam et un partenaire stratégique de l'ONU Environnement.",
    "whoWeAreValuesTitle": "Nos Valeurs Fondamentales",
    "whoWeAreVal1Title": "Action Positive",
    "whoWeAreVal1Desc": "Nous agissons concrètement sur le terrain pour transformer la volonté en résultats mesurables.",
    "whoWeAreVal2Title": "Unité & Inclusion",
    "whoWeAreVal2Desc": "Chaque individu peut apporter sa contribution pour préserver notre planète.",
    "whoWeAreVal3Title": "Transparence & Données",
    "whoWeAreVal3Desc": "Suivi numérique rigoureux des tonnages collectés et des certifications délivrées.",
    "whoWeAreCtaTitle": "Prêt à faire la différence ?",
    "whoWeAreCtaDesc": "Rejoignez des milliers de bénévoles et inscrivez-vous dès aujourd'hui pour le World Cleanup Day 2026.",
    "whatWeDoBadge": "4 Piliers d'Action",
    "whatWeDoTitle": "Ce Que Nous Faisons",
    "whatWeDoIntro": "Du ramassage sur les plages à la numérisation des données sur les déchets, nous développons des solutions durables.",
    "whatWeDoPillar1Title": "Campagnes de Nettoyage Nationales",
    "whatWeDoPillar1Desc": "Mobilisation simultanée de dizaines de milliers de personnes lors de la Journée Mondiale du Nettoyage.",
    "whatWeDoPillar2Title": "Éducation Écologique & Ateliers",
    "whatWeDoPillar2Desc": "Sensibilisation au tri à la source, aux écobriques et au mode de vie Zéro Déchet.",
    "whatWeDoPillar3Title": "Cartographie des Décharges Sauvages",
    "whatWeDoPillar3Desc": "Plateforme GPS citoyenne pour signaler les points noirs environnementaux.",
    "whatWeDoPillar4Title": "Économie Circulaire & RSE",
    "whatWeDoPillar4Desc": "Partenariats avec les recycleurs et accompagnement des entreprises dans leur transition verte.",
    "whatWeDoExploreProjectsBtn": "Explorer les Projets",
    "ourTeamBadge": "Direction & Coordinateurs",
    "ourTeamTitle": "L'équipe Let's do it! Vietnam",
    "ourTeamDesc": "Des leaders passionnés et déterminés à guider les actions environnementales à travers tout le pays.",
    "ourTeamJoinTitle": "Envie de devenir coordinateur régional ?",
    "ourTeamJoinDesc": "Nous recherchons toujours des jeunes passionnés pour diriger nos antennes dans les nouvelles provinces. Rejoignez le recrutement Core Team 2026/2026 dès aujourd'hui !",
    "ourTeamJoinBtn": "Postuler au Core Team",
    "ourPartnersBadge": "Réseau de Partenaires",
    "ourPartnersTitle": "Partenaires & Sponsors",
    "ourPartnersDesc": "Nous sommes fiers de collaborer avec des institutions, des universités et des entreprises engagées.",
    "becomePartnerBtn": "Devenir Partenaire",
    "getInvolvedTitle": "Rejoignez l'action dès aujourd'hui",
    "getInvolvedSubtitle": "Chaque geste compte pour protéger notre environnement.",
    "cardVolTitle": "Devenir bénévole",
    "cardVolDesc": "Rejoignez les points de nettoyage proches de chez vous et recevez votre équipement et certificat.",
    "cardVolBtn": "S'inscrire comme bénévole",
    "cardPartnerTitle": "Partenariat entreprise",
    "cardPartnerDesc": "Engagez votre organisation dans des actions écologiques à fort impact.",
    "cardPartnerBtn": "Devenir partenaire",
    "galleryBadge": "Moments d'action",
    "galleryTitle": "Galerie Photos & Médias",
    "gallerySubtitle": "Les sourires et l'énergie déployée tout au long de nos campagnes.",
    "galleryViewAll": "Voir toutes les photos",
    "mapTitle": "Carte nationale des points de nettoyage",
    "mapSubtitle": "Cliquez sur la carte pour signaler un point de déchets nécessitant un nettoyage.",
    "streets": "Rues",
    "satellite": "Satellite",
    "terrain": "Relief",
    "allProvinces": "Tout le Vietnam",
    "cleanupSpots": "Points de nettoyage",
    "pinNewLocation": "Nouveau point sélectionné",
    "postTrashSpotHere": "Signaler ce point ici",
    "viewDetails": "Voir détails",
    "registerNow": "S'inscrire",
    "footerDesc": "Mouvement civique mondial unissant les communautés pour un Vietnam vert, propre et durable.",
    "quickLinks": "Liens rapides",
    "contactInfo": "Informations de contact",
    "followUs": "Suivez-nous",
    "allRightsReserved": "Droits d'auteur © Let's do it! Vietnam. Tous droits réservés.",
    "newsPageBadge": "Actualités & Couverture médiatique",
    "newsPageTitleMedia": "Presse & Reportages télévisés sur nous",
    "newsPageTitleDefault": "Actualités & Actions environnementales",
    "newsPageSubtitle": "Retrouvez les dernières actualités, reportages télévisés, articles de fond et témoignages inspirants de nos campagnes de nettoyage.",
    "newsPageAddArticleBtn": "Publier un article / une actualité",
    "newsPageAllCategoriesLabel": "Tous les articles",
    "newsPagePendingBadge": "En attente de validation",
    "newsPageSourceLabel": "Source :",
    "newsPageReadMoreBtn": "Lire l'article",
    "newsPageBackToListBtn": "Retour à la liste",
    "newsPageSourceOriginalLabel": "Voir l'article original sur :",
    "newsPageDefaultSourceLabel": "Source originale",
    "newsCatAll": "Tous les articles",
    "newsCatNews": "Actualités",
    "newsCatMedia": "Médias sur nous",
    "newsCatPress": "Communiqués de presse",
    "newsCatImpact": "Témoignages d'impact",
    "projectsBadge": "Action Environnementale",
    "projectsTitle": "Campagnes & Projets Environnementaux Majeurs",
    "projectsSubtitle": "Choisissez une campagne dans votre région et agissez avec des milliers de bénévoles dès aujourd’hui.",
    "projectsAddBtn": "Créer une Nouvelle Campagne",
    "projectsAllCategoryLabel": "Toutes les Campagnes",
    "projectsDetailBtn": "Voir les Détails",
    "projectsJoinBtn": "Participer à la Campagne",
    "fullGalleryBadge": "Archives Photos & Vidéos",
    "fullGalleryTitle": "Galerie Documentaire & Photos",
    "fullGallerySubtitle": "Sourires et transformation des sites lors de chaque campagne Let's do it! Vietnam.",
    "fullGalleryAllYearsLabel": "Toutes les années",
    "fullGalleryYearPrefix": "Année",
    "fullGalleryUploadBtn": "Ajouter une Photo",
    "contactPageBadge": "Contactez-nous",
    "contactPageSubtitle": "Une question, un dépôt sauvage à signaler, ou l'envie de collaborer sur une campagne locale ? Envoyez-nous votre message.",
    "contactPageFindUsTitle": "Vous pouvez nous trouver à",
    "contactPageEmailLabel": "ADRESSE EMAIL",
    "contactPagePhoneLabel1": "NUMÉRO DE TÉLÉPHONE",
    "contactPagePhoneLabel2": "NUMÉRO DE TÉLÉPHONE",
    "contactPhone1Default": "035.872.6755 (M. Son)",
    "contactPhone2Default": "0968.514.882 (Mme Tu)",
    "contactSubjectOpt1": "Inscription bénévole & Campagnes",
    "contactSubjectOpt2": "Partenariat d'entreprise & Mécénat ESG",
    "contactSubjectOpt3": "Signaler une décharge sauvage",
    "contactSubjectOpt4": "Questions générales & Médias",
    "contactPageFormTitle": "Envoyer un message à notre équipe",
    "contactPageThankYouTitle": "Merci de nous avoir contactés !",
    "contactPageThankYouMsgPrefix": "Votre message a bien été reçu. Notre équipe vous répondra par email à ",
    "contactPageThankYouMsgSuffix": " dans les plus brefs délais.",
    "contactPageSendAnotherBtn": "Envoyer un autre message",
    "contactPageNameLabel": "Nom complet *",
    "contactPageEmailFieldLabel": "Adresse email *",
    "contactPagePhoneFieldLabel": "Numéro de téléphone (10 chiffres)",
    "contactPageSubjectLabel": "Sujet",
    "contactPageMessageLabel": "Message *",
    "contactPageSubmitBtn": "Envoyer le message"
  },
  "ja": {
    "selectLanguage": "言語を選択",
    "topBarAnnouncement": "ワールドクリーンアップデー2026のボランティア全国募集を開始しました！",
    "topBarTagline": "Let's do it! Vietnam - 緑豊かで清潔、ゴミのないベトナムを共に創りましょう！",
    "navWhoWeAre": "私たちについて",
    "navWhatWeDo": "活動内容",
    "navOurTeam": "チーム紹介",
    "navOurPartners": "パートナー",
    "navProject": "プロジェクト",
    "navOther": "その他",
    "navMediaOnUs": "メディア掲載",
    "navNews": "ニュース",
    "navVideos": "動画",
    "videosPageBadge": "行動を起こそう",
    "videosPageTitle": "変化の瞬間を記録する",
    "videosPageSubtitle": "ワールドクリーンアップデーの活動を記録したテレビ特集やドキュメンタリー映像。",
    "videosPageCountSuffix": "本",
    "videosPageAddBtn": "新しい動画を追加",
    "videosPageEmptyTitle": "動画がまだありません",
    "videosPageEmptyDesc": "YouTubeリンクを貼り付けて動画を共有してください",
    "navContactUs": "お問い合わせ",
    "navMap": "クリーンマップ",
    "projectWcd": "ワールドクリーンアップデー",
    "projectEnvDay": "世界環境デー",
    "projectGreenOcean": "グリーンオーシャン計画",
    "projectYoungWildlife": "野生動物保護プロジェクト",
    "projectWorkshop": "コミュニティワークショップ",
    "viewAllProjects": "全プロジェクトを見る »",
    "adminDb": "データベース管理",
    "register": "登録",
    "login": "ログイン",
    "joinVolunteer": "ボランティア応募",
    "profile": "プロフィール",
    "logout": "ログアウト",
    "signUpSignIn": "ログイン",
    "roleAdmin": "管理者",
    "roleVolunteer": "ボランティア",
    "close": "閉じる",
    "privacyPolicy": "プライバシーポリシー",
    "termsOfService": "ボランティア規約",
    "contactBubbleTitle": "サポート＆お問い合わせ",
    "contactBubbleSubtitle": "いつでもお気軽にご相談ください",
    "contactBubbleOpenBtn": "メッセージを送る",
    "heroSlide1Badge": "ワールドクリーンアップデー 2026 • 環境のための10年の歩み",
    "heroSlide1Title": "ワールドクリーンアップデー",
    "heroSlide1Desc": "5,000人以上の若者、家族、組織が緑豊かなベトナムのために団結します。",
    "registerNowBtn": "今すぐボランティア参加",
    "exploreCampaignsBtn": "キャンペーンを見る",
    "heroSlideTab1": "メインバナー",
    "heroSlideTab2": "グローバルメッセージ",
    "heroSlide2Badge": "世界規模のキャンペーン",
    "heroSlide2Title1": "ワールドクリーンアップデー:",
    "heroSlide2Title2": "地球規模の影響、地域からの行動",
    "heroSlide2Desc": "熱意あるボランティアと共に、ゴミ分別と環境保護への意識向上を目指します。",
    "featureProvinces": "全国63省市が参加",
    "featureCert": "公式ボランティア証明書発行",
    "featureGear": "清掃用具・保護具を無料提供",
    "joinNextEvent": "次のイベントに参加する",
    "exploreMap": "クリーンマップを見る",
    "aboutBadge": "環境イニシアチブについて",
    "aboutTitle": "Let's do it! Vietnam ムーブメント",
    "aboutP1": "190カ国以上で数百万人が参加する、世界最大の市民環境保護運動です。",
    "aboutP2": "2015年以来、ゴミ拾いだけでなくゴミゼロの習慣づけに取り組んでいます。",
    "statTons": "回収されたゴミの量 (トン)",
    "statTonsSub": "安全に回収・分別完了",
    "statVolunteers": "参加ボランティア総数",
    "statVolunteersSub": "全国63省市にて活動中",
    "statEvents": "開催されたイベント数",
    "statEventsSub": "全国で同時開催",
    "whoWeAreBadge": "10年にわたるコミュニティの歩み",
    "whoWeAreTitlePrefix": "私たちの組織",
    "whoWeAreIntro": "2015年に設立された Let's do it! Vietnam は、エストニア本部の国際環境ネットワーク Let's Do It World に加盟する非営利団体です。",
    "whoWeAreMissionTitle": "ミッション",
    "whoWeAreMissionDesc": "全国規模の清掃運動とデジタルマップ技術を活用し、市民の環境意識向上と行動を促進します。",
    "whoWeAreVisionTitle": "ビジョン 2030",
    "whoWeAreVisionDesc": "ベトナム最大の市民環境運動へと成長し、国連環境計画(UNEP)のパートナーとして循環型社会を築きます。",
    "whoWeAreValuesTitle": "私たちのコアバリュー",
    "whoWeAreVal1Title": "積極的な行動",
    "whoWeAreVal1Desc": "言葉だけでなく実際に清掃活動を行い、目に見える成果を生み出します。",
    "whoWeAreVal2Title": "団結とインクルージョン",
    "whoWeAreVal2Desc": "年齢や職業に関わらず、すべての人が地球環境のために貢献できます。",
    "whoWeAreVal3Title": "透明性とデータ主導",
    "whoWeAreVal3Desc": "回収量や資金、証明書をデジタルデータベースで正確に管理・公開します。",
    "whoWeAreCtaTitle": "一緒に変化を起こしませんか？",
    "whoWeAreCtaDesc": "今すぐワールドクリーンアップデー2026に登録して、仲間と共に活動しましょう。",
    "whatWeDoBadge": "4つの行動の柱",
    "whatWeDoTitle": "私たちの活動",
    "whatWeDoIntro": "海岸のゴミ拾いから海洋ゴミデータのデジタル化まで、持続可能な解決策を提供します。",
    "whatWeDoPillar1Title": "全国一斉清掃キャンペーン",
    "whatWeDoPillar1Desc": "ワールドクリーンアップデーに合わせて数万人が全国で一斉に清掃を実施。",
    "whatWeDoPillar2Title": "環境教育＆ワークショップ",
    "whatWeDoPillar2Desc": "ゴミ分別、エコブリック作り、ゼロウェイスト生活の普及学習。",
    "whatWeDoPillar3Title": "ゴミ不法投棄デジタルマップ",
    "whatWeDoPillar3Desc": "GPSを活用し、地域の汚染ホットスポットを市民が報告・追跡。",
    "whatWeDoPillar4Title": "循環型経済＆ESG連携",
    "whatWeDoPillar4Desc": "リサイクル企業や企業パートナーとの連携によるプラスチック削減推進。",
    "whatWeDoExploreProjectsBtn": "プロジェクトを見る",
    "ourTeamBadge": "運営委員会・コーディネーター",
    "ourTeamTitle": "Let's do it! Vietnam チーム",
    "ourTeamDesc": "ベトナム全土で環境プロジェクトを牽引する情熱的なメンバーたち。",
    "ourTeamJoinTitle": "地域コーディネーターになりませんか?",
    "ourTeamJoinDesc": "新しい省の拠点を担う情熱的な若者を常に募集しています。Core Team 2026/2026の募集に今すぐ参加しましょう!",
    "ourTeamJoinBtn": "Core Teamに応募する",
    "ourPartnersBadge": "パートナーネットワーク",
    "ourPartnersTitle": "パートナー＆スポンサー",
    "ourPartnersDesc": "政府機関、国際機関、大学、先進企業からのご支援に深く感謝いたします。",
    "becomePartnerBtn": "パートナーになる",
    "getInvolvedTitle": "今日から参加しましょう",
    "getInvolvedSubtitle": "あなたの小さな一歩が大きな変化をもたらします。",
    "cardVolTitle": "ボランティアに応募する",
    "cardVolDesc": "お近くの清掃ポイントに参加して、限定Tシャツと公式認定証を受け取りましょう。",
    "cardVolBtn": "ボランティア登録",
    "cardPartnerTitle": "企業・団体パートナーシップ",
    "cardPartnerDesc": "CSR・ESG活動として社内清掃イベントや協賛をご検討ください。",
    "cardPartnerBtn": "パートナーに応募",
    "galleryBadge": "活動の瞬間",
    "galleryTitle": "フォト＆メディアギャラリー",
    "gallerySubtitle": "これまでの清掃活動での笑顔と感動の記録。",
    "galleryViewAll": "すべての写真を見る",
    "mapTitle": "全国クリーンアップスポットマップ",
    "mapSubtitle": "地図上をクリックして、清掃が必要な場所をピン留め・報告してください。",
    "streets": "標準マップ",
    "satellite": "航空写真",
    "terrain": "地形図",
    "allProvinces": "ベトナム全土",
    "cleanupSpots": "清掃スポット",
    "pinNewLocation": "新しい場所を指定",
    "postTrashSpotHere": "この場所のゴミ情報を投稿",
    "viewDetails": "詳細を見る",
    "registerNow": "登録する",
    "footerDesc": "緑豊かで持続可能なベトナムを目指すグローバル市民環境保護ネットワーク。",
    "quickLinks": "クイックリンク",
    "contactInfo": "お問い合わせ先",
    "followUs": "フォローする",
    "allRightsReserved": "著作権 © Let's do it! Vietnam. 無断転載を禁じます。",
    "newsPageBadge": "ニュース＆メディア掲載",
    "newsPageTitleMedia": "私たちに関する報道・テレビ特集",
    "newsPageTitleDefault": "ニュース＆環境活動",
    "newsPageSubtitle": "最新ニュース、テレビ特集、詳細記事、そして実際の清掃活動から生まれた感動のストーリーをお届けします。",
    "newsPageAddArticleBtn": "記事・ニュースを投稿する",
    "newsPageAllCategoriesLabel": "すべての記事",
    "newsPagePendingBadge": "承認待ち",
    "newsPageSourceLabel": "出典：",
    "newsPageReadMoreBtn": "記事を読む",
    "newsPageBackToListBtn": "一覧に戻る",
    "newsPageSourceOriginalLabel": "元記事はこちらでご覧いただけます：",
    "newsPageDefaultSourceLabel": "元記事",
    "newsCatAll": "すべての記事",
    "newsCatNews": "ニュース",
    "newsCatMedia": "メディア掲載",
    "newsCatPress": "プレスリリース",
    "newsCatImpact": "活動ストーリー",
    "projectsBadge": "環境アクション",
    "projectsTitle": "主要環境プロジェクト＆キャンペーン",
    "projectsSubtitle": "お近くのキャンペーンを選び、全国の仲間と共に今日から行動しましょう。",
    "projectsAddBtn": "清掃キャンペーンを新設する",
    "projectsAllCategoryLabel": "すべてのキャンペーン",
    "projectsDetailBtn": "詳細を見る",
    "projectsJoinBtn": "参加申込",
    "fullGalleryBadge": "写真＆動画アーカイブ",
    "fullGalleryTitle": "ドキュメンタリー＆フォトギャラリー",
    "fullGallerySubtitle": "Let's do it! Vietnam キャンペーンを通じて生まれた笑顔と環境の劇的な変化。",
    "fullGalleryAllYearsLabel": "すべての年",
    "fullGalleryYearPrefix": "年",
    "fullGalleryUploadBtn": "写真を投稿する",
    "contactPageBadge": "お気軽にご連絡ください",
    "contactPageSubtitle": "ご質問や不法投棄の通報、地域キャンペーンでの連携をご希望の方は、ぜひメッセージをお送りください。",
    "contactPageFindUsTitle": "お問い合わせ先・所在地",
    "contactPageEmailLabel": "メールアドレス",
    "contactPagePhoneLabel1": "電話番号",
    "contactPagePhoneLabel2": "電話番号",
    "contactPhone1Default": "035.872.6755 (ソン氏)",
    "contactPhone2Default": "0968.514.882 (トゥ氏)",
    "contactSubjectOpt1": "ボランティア登録・イベント参加",
    "contactSubjectOpt2": "企業連携・ESG協賛",
    "contactSubjectOpt3": "不法投棄ゴミの通報",
    "contactSubjectOpt4": "メディア取材・その他のお問い合わせ",
    "contactPageFormTitle": "運営チームにメッセージを送る",
    "contactPageThankYouTitle": "ご連絡ありがとうございます！",
    "contactPageThankYouMsgPrefix": "メッセージを受け付けました。運営チームより ",
    "contactPageThankYouMsgSuffix": " 宛てに、できるだけ早くご返信いたします。",
    "contactPageSendAnotherBtn": "別のメッセージを送る",
    "contactPageNameLabel": "お名前 *",
    "contactPageEmailFieldLabel": "メールアドレス *",
    "contactPagePhoneFieldLabel": "電話番号（10桁）",
    "contactPageSubjectLabel": "件名",
    "contactPageMessageLabel": "メッセージ内容 *",
    "contactPageSubmitBtn": "メッセージを送信"
  },
  "ko": {
    "selectLanguage": "언어 선택",
    "topBarAnnouncement": "2026 세계 청소의 날 전국 자원봉사자 모집이 시작되었습니다!",
    "topBarTagline": "Let's do it! Vietnam - 깨끗하고 쓰레기 없는 베트남을 함께 만듭니다!",
    "navWhoWeAre": "소개",
    "navWhatWeDo": "주요 활동",
    "navOurTeam": "팀 소개",
    "navOurPartners": "파트너",
    "navProject": "프로젝트",
    "navOther": "기타",
    "navMediaOnUs": "보도자료",
    "navNews": "뉴스",
    "navVideos": "동영상",
    "videosPageBadge": "실천하기",
    "videosPageTitle": "변화의 순간을 담다",
    "videosPageSubtitle": "방송 보도 및 정화 활동 현장을 담은 다큐멘터리 영상들을 감상하세요.",
    "videosPageCountSuffix": "개",
    "videosPageAddBtn": "새 동영상 추가",
    "videosPageEmptyTitle": "등록된 동영상이 없습니다",
    "videosPageEmptyDesc": "YouTube 링크를 붙여넣어 동영상을 공유하세요",
    "navContactUs": "문의하기",
    "navMap": "청소 지도",
    "projectWcd": "세계 청소의 날",
    "projectEnvDay": "세계 환경의 날",
    "projectGreenOcean": "그린 오션 캠페인",
    "projectYoungWildlife": "야생동물 보호 프로젝트",
    "projectWorkshop": "커뮤니티 워크숍",
    "viewAllProjects": "모든 캠페인 보기 »",
    "adminDb": "DB 관리자",
    "register": "회원가입",
    "login": "로그인",
    "joinVolunteer": "봉사 신청",
    "profile": "내 프로필",
    "logout": "로그아웃",
    "signUpSignIn": "로그인",
    "roleAdmin": "관리자",
    "roleVolunteer": "자원봉사자",
    "close": "닫기",
    "privacyPolicy": "개인정보처리방침",
    "termsOfService": "이용약관",
    "contactBubbleTitle": "빠른 지원 및 문의",
    "contactBubbleSubtitle": "언제든 문의해 주세요",
    "contactBubbleOpenBtn": "문의 페이지 열기",
    "heroSlide1Badge": "2026 세계 청소의 날 • 환경을 위한 10년의 여정",
    "heroSlide1Title": "세계 청소의 날",
    "heroSlide1Desc": "5,000명 이상의 청년과 가족, 단체들이 함께 친환경 베트남을 만들어갑니다.",
    "registerNowBtn": "지금 바로 봉사 신청",
    "exploreCampaignsBtn": "캠페인 둘러보기",
    "heroSlideTab1": "메인 배너",
    "heroSlideTab2": "글로벌 메시지",
    "heroSlide2Badge": "글로벌 캠페인",
    "heroSlide2Title1": "세계 청소의 날:",
    "heroSlide2Title2": "지역 실천, 글로벌 변화",
    "heroSlide2Desc": "열정적인 자원봉사자들과 함께 쓰레기 분리배출 및 환경 인식 개선에 앞장섭니다.",
    "featureProvinces": "63개 성·시 참여",
    "featureCert": "공식 자원봉사 수료증 발급",
    "featureGear": "안전 장비 무료 제공",
    "joinNextEvent": "다음 이벤트 참여하기",
    "exploreMap": "청소 지도 보기",
    "aboutBadge": "환경 이니셔티브 소개",
    "aboutTitle": "Let's do it! Vietnam 운동",
    "aboutP1": "190개국 이상에서 수백만 명이 참여하는 세계 최대 규모의 시민 환경 운동입니다.",
    "aboutP2": "2015년부터 정화 활동과 함께 제로 웨이스트 습관을 장려하고 있습니다.",
    "statTons": "수거된 쓰레기 (톤)",
    "statTonsSub": "안전하게 수거 및 분리 완료",
    "statVolunteers": "참여 자원봉사자 수",
    "statVolunteersSub": "베트남 63개 성·시 전역",
    "statEvents": "개최된 환경 캠페인",
    "statEventsSub": "전국 동시 진행",
    "whoWeAreBadge": "10년간의 지역사회 동행",
    "whoWeAreTitlePrefix": "우리는",
    "whoWeAreIntro": "2015년 설립된 Let's do it! Vietnam은 에스토니아 본부의 국제 환경 네트워크 Let's Do It World 산하 비영리 단체입니다.",
    "whoWeAreMissionTitle": "우리의 사명",
    "whoWeAreMissionDesc": "전국 정화 캠페인과 디지털 오염 지도 기술을 통해 시민 환경 의식을 일깨웁니다.",
    "whoWeAreVisionTitle": "비전 2030",
    "whoWeAreVisionDesc": "베트남 최대 시민 환경 운동으로 성장하여 UNEP의 공식 파트너로서 지속가능한 미래를 만듭니다.",
    "whoWeAreValuesTitle": "우리의 핵심 가치",
    "whoWeAreVal1Title": "적극적인 실천",
    "whoWeAreVal1Desc": "말뿐만 아니라 현장에서 직접 청소하며 실질적인 변화를 창출합니다.",
    "whoWeAreVal2Title": "연대와 포용",
    "whoWeAreVal2Desc": "누구나 나이와 배경에 상관없이 지구를 위해 기여할 수 있습니다.",
    "whoWeAreVal3Title": "투명성과 데이터",
    "whoWeAreVal3Desc": "디지털 데이터베이스를 통해 수거량과 활동 기록을 투명하게 관리합니다.",
    "whoWeAreCtaTitle": "변화를 만들 준비가 되셨나요?",
    "whoWeAreCtaDesc": "지금 2026 세계 청소의 날에 등록하고 함께 행동하세요.",
    "whatWeDoBadge": "4대 핵심 행동 축",
    "whatWeDoTitle": "주요 활동",
    "whatWeDoIntro": "해변 쓰레기 수거부터 해양 폐기물 데이터 디지털화까지 종합 솔루션을 구축합니다.",
    "whatWeDoPillar1Title": "전국 청소 캠페인",
    "whatWeDoPillar1Desc": "세계 청소의 날을 맞아 수만 명이 전국 각지에서 동시에 정화 활동 진행.",
    "whatWeDoPillar2Title": "생태 교육 및 워크숍",
    "whatWeDoPillar2Desc": "분리수거 교육, 에코브릭 제작, 제로 웨이스트 라이프스타일 전파.",
    "whatWeDoPillar3Title": "쓰레기 핫스팟 디지털 지도",
    "whatWeDoPillar3Desc": "GPS 기반으로 시민들이 불법 투기 지역을 직접 제보하고 추적 관리.",
    "whatWeDoPillar4Title": "순환 경제 및 ESG 파트너십",
    "whatWeDoPillar4Desc": "재활용 기업 연계 및 기업의 친환경 책임(EPR) 실천 지원.",
    "whatWeDoExploreProjectsBtn": "프로젝트 둘러보기",
    "ourTeamBadge": "운영진 및 코디네이터",
    "ourTeamTitle": "Let's do it! Vietnam 팀",
    "ourTeamDesc": "베트남 전역에서 환경 프로젝트를 이끄는 열정적인 리더들.",
    "ourTeamJoinTitle": "지역 코디네이터가 되고 싶으신가요?",
    "ourTeamJoinDesc": "새로운 지역 거점을 이끌어갈 열정적인 청년을 항상 찾고 있습니다. 지금 바로 Core Team 2026/2026 모집에 참여하세요!",
    "ourTeamJoinBtn": "Core Team 지원하기",
    "ourPartnersBadge": "파트너 네트워크",
    "ourPartnersTitle": "파트너 & 후원사",
    "ourPartnersDesc": "정부 기관, 국제기구, 대학, 선도 기업의 후원에 진심으로 감사드립니다.",
    "becomePartnerBtn": "파트너 신청",
    "getInvolvedTitle": "지금 함께 행동하세요",
    "getInvolvedSubtitle": "작은 실천이 모여 큰 변화를 만듭니다.",
    "cardVolTitle": "자원봉사자 신청",
    "cardVolDesc": "가까운 정화 장소에 참여하고 공식 수료증과 물품을 받으세요.",
    "cardVolBtn": "봉사자 등록",
    "cardPartnerTitle": "기업 및 단체 파트너십",
    "cardPartnerDesc": "CSR/ESG 활동으로 지속가능한 사회공헌을 실천하세요.",
    "cardPartnerBtn": "파트너 신청",
    "galleryBadge": "활동의 순간들",
    "galleryTitle": "사진 & 미디어 갤러리",
    "gallerySubtitle": "전국 캠페인 현장의 열정과 미소.",
    "galleryViewAll": "사진 전체 보기",
    "mapTitle": "전국 정화 장소 지도",
    "mapSubtitle": "지도를 클릭하여 청소가 필요한 오염 지점을 등록하세요.",
    "streets": "일반 지도",
    "satellite": "위성 지도",
    "terrain": "지형도",
    "allProvinces": "전국",
    "cleanupSpots": "청소 구역",
    "pinNewLocation": "새 위치 핀 추가",
    "postTrashSpotHere": "이곳의 쓰레기 제보하기",
    "viewDetails": "상세보기",
    "registerNow": "등록하기",
    "footerDesc": "녹색 베트남을 위해 활동하는 글로벌 시민 환경 보호 네트워크.",
    "quickLinks": "빠른 링크",
    "contactInfo": "연락처 정보",
    "followUs": "팔로우하기",
    "allRightsReserved": "저작권 © Let's do it! Vietnam. All rights reserved.",
    "newsPageBadge": "뉴스 & 언론 보도",
    "newsPageTitleMedia": "저희에 대한 언론 및 방송 보도",
    "newsPageTitleDefault": "뉴스 & 환경 활동 소식",
    "newsPageSubtitle": "최신 소식, 방송 특집, 심층 기사와 실제 정화 캠페인에서 전해지는 감동적인 이야기를 만나보세요.",
    "newsPageAddArticleBtn": "새 기사 / 소식 등록하기",
    "newsPageAllCategoriesLabel": "전체 기사",
    "newsPagePendingBadge": "승인 대기 중",
    "newsPageSourceLabel": "출처:",
    "newsPageReadMoreBtn": "기사 읽기",
    "newsPageBackToListBtn": "목록으로 돌아가기",
    "newsPageSourceOriginalLabel": "원문 기사 보기:",
    "newsPageDefaultSourceLabel": "원문 출처",
    "newsCatAll": "전체 기사",
    "newsCatNews": "뉴스",
    "newsCatMedia": "언론 보도",
    "newsCatPress": "보도자료",
    "newsCatImpact": "참여 스토리",
    "projectsBadge": "환경 보호 실천",
    "projectsTitle": "주요 환경 캠페인 및 프로젝트",
    "projectsSubtitle": "지역 내 캠페인을 선택하고 수천 명의 자원봉사자들과 함께 지금 행동하세요.",
    "projectsAddBtn": "새 정화 캠페인 등록",
    "projectsAllCategoryLabel": "전체 캠페인",
    "projectsDetailBtn": "캠페인 상세 보기",
    "projectsJoinBtn": "참여 신청하기",
    "fullGalleryBadge": "사진 및 영상 아카이브",
    "fullGalleryTitle": "다큐멘터리 및 사진 갤러리",
    "fullGallerySubtitle": "Let's do it! Vietnam 캠페인을 통해 변화하는 환경과 소중한 미소들.",
    "fullGalleryAllYearsLabel": "전체 연도",
    "fullGalleryYearPrefix": "년",
    "fullGalleryUploadBtn": "새 사진 업로드",
    "contactPageBadge": "지금 바로 연락하세요",
    "contactPageSubtitle": "궁금한 점이 있거나 무단 투기 지역을 제보하고 싶으신가요? 지역 캠페인 협력을 원하시면 언제든 메시지를 보내주세요.",
    "contactPageFindUsTitle": "아래에서 저희에게 연락하세요",
    "contactPageEmailLabel": "이메일 주소",
    "contactPagePhoneLabel1": "전화번호",
    "contactPagePhoneLabel2": "전화번호",
    "contactPhone1Default": "035.872.6755 (손 담당자)",
    "contactPhone2Default": "0968.514.882 (투 담당자)",
    "contactSubjectOpt1": "자원봉사 등록 및 캠페인 참여",
    "contactSubjectOpt2": "기업 파트너십 및 ESG 후원",
    "contactSubjectOpt3": "불법 쓰레기 투기 제보",
    "contactSubjectOpt4": "일반 문의 및 언론 보도",
    "contactPageFormTitle": "운영팀에 메시지 보내기",
    "contactPageThankYouTitle": "연락해 주셔서 감사합니다!",
    "contactPageThankYouMsgPrefix": "메시지가 정상적으로 접수되었습니다. 운영팀에서 ",
    "contactPageThankYouMsgSuffix": " 주소로 최대한 빠르게 답변드리겠습니다.",
    "contactPageSendAnotherBtn": "다른 메시지 보내기",
    "contactPageNameLabel": "성명 *",
    "contactPageEmailFieldLabel": "이메일 주소 *",
    "contactPagePhoneFieldLabel": "전화번호 (숫자 10자리)",
    "contactPageSubjectLabel": "제목",
    "contactPageMessageLabel": "메시지 내용 *",
    "contactPageSubmitBtn": "메시지 보내기"
  },
  "zh": {
    "selectLanguage": "选择语言",
    "topBarAnnouncement": "2026年世界清洁日全国志愿者招募现已开启！",
    "topBarTagline": "Let's do it! Vietnam - 携手共建绿色、清洁、零废弃的越南！",
    "navWhoWeAre": "关于我们",
    "navWhatWeDo": "核心行动",
    "navOurTeam": "团队成员",
    "navOurPartners": "合作伙伴",
    "navProject": "环保项目",
    "navOther": "其他",
    "navMediaOnUs": "媒体报道",
    "navNews": "新闻动态",
    "navVideos": "视频",
    "videosPageBadge": "采取行动",
    "videosPageTitle": "定格蜕变，记录前行",
    "videosPageSubtitle": "观看电视新闻专题报道与清洁行动现场精彩纪录片。",
    "videosPageCountSuffix": "个视频",
    "videosPageAddBtn": "添加新视频",
    "videosPageEmptyTitle": "暂无视频",
    "videosPageEmptyDesc": "粘贴YouTube链接即可分享视频",
    "navContactUs": "联系我们",
    "navMap": "清洁地图",
    "projectWcd": "世界清洁日",
    "projectEnvDay": "世界环境日",
    "projectGreenOcean": "绿色海洋行动",
    "projectYoungWildlife": "野生动物保护行动",
    "projectWorkshop": "社区环保工作坊",
    "viewAllProjects": "查看全部项目 »",
    "adminDb": "数据库管理",
    "register": "注册",
    "login": "登录",
    "joinVolunteer": "志愿报名",
    "profile": "个人中心",
    "logout": "退出登录",
    "signUpSignIn": "登录",
    "roleAdmin": "管理员",
    "roleVolunteer": "志愿者",
    "close": "关闭",
    "privacyPolicy": "隐私政策",
    "termsOfService": "志愿服务条款",
    "contactBubbleTitle": "快速支持与咨询",
    "contactBubbleSubtitle": "竭诚为您解答任何疑问",
    "contactBubbleOpenBtn": "发送留言",
    "heroSlide1Badge": "2026世界清洁日 • 守护环境十载同行",
    "heroSlide1Title": "世界清洁日",
    "heroSlide1Desc": "超过5000名青年、家庭与机构携手共筑绿色无废越南。",
    "registerNowBtn": "立即报名参加",
    "exploreCampaignsBtn": "探索环保活动",
    "heroSlideTab1": "主题海报",
    "heroSlideTab2": "全球倡议",
    "heroSlide2Badge": "全球环保行动",
    "heroSlide2Title1": "世界清洁日：",
    "heroSlide2Title2": "立足本土，影响全球",
    "heroSlide2Desc": "汇聚数万名热心志愿者，积极推进垃圾分类与环保意识提升。",
    "featureProvinces": "全国63省市共同参与",
    "featureCert": "颁发官方志愿服务证书",
    "featureGear": "免费提供专业防护装备",
    "joinNextEvent": "参与下一场活动",
    "exploreMap": "查看清洁地图",
    "aboutBadge": "环保倡议介绍",
    "aboutTitle": "Let's do it! Vietnam 运动",
    "aboutP1": "全球最大的公民环保行动，在190多个国家汇聚了数百万名志愿者。",
    "aboutP2": "自2015年起，我们不仅清理垃圾，更倡导零废弃的生活方式。",
    "statTons": "累计清理垃圾（吨）",
    "statTonsSub": "安全收集与合规分类",
    "statVolunteers": "参与志愿者总数",
    "statVolunteersSub": "遍布越南63个省市",
    "statEvents": "组织环保活动场次",
    "statEventsSub": "全国多地同步开展",
    "whoWeAreBadge": "十年社区环保同行",
    "whoWeAreTitlePrefix": "我们是",
    "whoWeAreIntro": "Let's do it! Vietnam 成立于2015年，隶属于爱沙尼亚全球网络 Let's Do It World，致力于建设清洁美丽的绿色越南。",
    "whoWeAreMissionTitle": "我们的使命",
    "whoWeAreMissionDesc": "通过全国清洁活动与数字化污染地图，赋能数百万公众积极践行环保。",
    "whoWeAreVisionTitle": "2030年愿景",
    "whoWeAreVisionDesc": "成为越南最具影响力的公民环保运动，并作为联合国环境规划署(UNEP)的战略合作伙伴。",
    "whoWeAreValuesTitle": "我们的核心价值观",
    "whoWeAreVal1Title": "积极行动",
    "whoWeAreVal1Desc": "不仅发声宣传，更亲力亲为清理环境，创造看得见的改变。",
    "whoWeAreVal2Title": "团结包容",
    "whoWeAreVal2Desc": "无论年龄与背景，每个人都能为自然生态贡献一份力量。",
    "whoWeAreVal3Title": "透明与数据化",
    "whoWeAreVal3Desc": "依托数字数据库精准统计垃圾回收量与志愿服务认证。",
    "whoWeAreCtaTitle": "准备好做出改变了吗？",
    "whoWeAreCtaDesc": "立即报名参加2026年世界清洁日，与数千名志愿者并肩同行。",
    "whatWeDoBadge": "四大核心行动支柱",
    "whatWeDoTitle": "核心行动",
    "whatWeDoIntro": "从海滩拾垃圾到海洋废弃物数字化统计，打造全方位的可持续解决方案。",
    "whatWeDoPillar1Title": "全国清洁行动",
    "whatWeDoPillar1Desc": "在世界清洁日组织数万人同时在全国各地开展清理行动。",
    "whatWeDoPillar2Title": "生态教育与工坊",
    "whatWeDoPillar2Desc": "开展垃圾源头分类、生态砖制作及零废弃生活方式科普。",
    "whatWeDoPillar3Title": "污染黑点数字地图",
    "whatWeDoPillar3Desc": "运用GPS与数字平台让公众实时上报和追踪垃圾非法堆放点。",
    "whatWeDoPillar4Title": "循环经济与ESG合作",
    "whatWeDoPillar4Desc": "连接回收企业，协助企业落实生产者责任延伸(EPR)和减塑目标。",
    "whatWeDoExploreProjectsBtn": "浏览环保项目",
    "ourTeamBadge": "管理团队与协调员",
    "ourTeamTitle": "Let's do it! Vietnam 团队",
    "ourTeamDesc": "带领全国各地环保活动充满激情的骨干力量。",
    "ourTeamJoinTitle": "想成为地区协调员吗?",
    "ourTeamJoinDesc": "我们一直在寻找充满热情的年轻人,负责新省份的联络点。立即加入Core Team 2026/2026招募!",
    "ourTeamJoinBtn": "申请加入Core Team",
    "ourPartnersBadge": "合作伙伴网络",
    "ourPartnersTitle": "合作伙伴与赞助商",
    "ourPartnersDesc": "感谢政府机构、国际组织、高校及企业的大力支持与信任。",
    "becomePartnerBtn": "申请成为合作伙伴",
    "getInvolvedTitle": "立即行动，从我做起",
    "getInvolvedSubtitle": "您的每一次参与都将为地球带来深远的积极影响。",
    "cardVolTitle": "报名成为志愿者",
    "cardVolDesc": "加入您附近的清洁点，获取志愿服装、安全工具和官方证书。",
    "cardVolBtn": "志愿者报名",
    "cardPartnerTitle": "企业与机构合作",
    "cardPartnerDesc": "通过企业社会责任(CSR/ESG)合作组织清洁日或项目赞助。",
    "cardPartnerBtn": "成为合作伙伴",
    "galleryBadge": "行动瞬间",
    "galleryTitle": "精彩图片与媒体中心",
    "gallerySubtitle": "记录每一次清洁行动中的汗水、笑容与转变。",
    "galleryViewAll": "查看所有照片",
    "mapTitle": "全国清洁点热力地图",
    "mapSubtitle": "点击地图任意位置即可添加坐标并上报需要清理的垃圾点。",
    "streets": "街道地图",
    "satellite": "卫星遥感",
    "terrain": "地形地貌",
    "allProvinces": "全越南",
    "cleanupSpots": "清洁点位",
    "pinNewLocation": "已标记新位置",
    "postTrashSpotHere": "在此上报垃圾点",
    "viewDetails": "查看详情",
    "registerNow": "立即注册",
    "footerDesc": "致力于建设绿色、清洁、可持续越南的全球公民环保网络。",
    "quickLinks": "快速链接",
    "contactInfo": "联系方式",
    "followUs": "关注我们",
    "allRightsReserved": "版权所有 © Let's do it! Vietnam. 保留所有权利。",
    "newsPageBadge": "新闻与媒体报道",
    "newsPageTitleMedia": "关于我们的新闻与电视报道",
    "newsPageTitleDefault": "新闻与环保活动动态",
    "newsPageSubtitle": "获取最新时事新闻、电视台专题报道、深度文章，以及来自真实清洁行动现场的感人故事。",
    "newsPageAddArticleBtn": "发布新文章 / 新闻",
    "newsPageAllCategoriesLabel": "全部文章",
    "newsPagePendingBadge": "待审核",
    "newsPageSourceLabel": "来源：",
    "newsPageReadMoreBtn": "阅读全文",
    "newsPageBackToListBtn": "返回列表",
    "newsPageSourceOriginalLabel": "查看原文报道：",
    "newsPageDefaultSourceLabel": "原始来源",
    "newsCatAll": "全部文章",
    "newsCatNews": "新闻动态",
    "newsCatMedia": "媒体报道",
    "newsCatPress": "官方通告",
    "newsCatImpact": "影响故事",
    "projectsBadge": "环保行动",
    "projectsTitle": "核心环保活动与重大项目",
    "projectsSubtitle": "选择您所在地区的环保活动，立即与数千名志愿者并肩行动。",
    "projectsAddBtn": "发起新的清洁活动",
    "projectsAllCategoryLabel": "全部项目",
    "projectsDetailBtn": "查看活动详情",
    "projectsJoinBtn": "立即报名参与",
    "fullGalleryBadge": "影像资料库",
    "fullGalleryTitle": "纪实影像与活动画廊",
    "fullGallerySubtitle": "记录每一次 Let's do it! Vietnam 环保行动中环境的美丽蜕变。",
    "fullGalleryAllYearsLabel": "全部年份",
    "fullGalleryYearPrefix": "年",
    "fullGalleryUploadBtn": "上传新照片",
    "contactPageBadge": "直接联系我们",
    "contactPageSubtitle": "如果您有疑问、想举报非法垃圾堆放点，或希望在当地开展合作活动，欢迎与我们联系。",
    "contactPageFindUsTitle": "联系方式与地址",
    "contactPageEmailLabel": "电子邮箱",
    "contactPagePhoneLabel1": "联系电话",
    "contactPagePhoneLabel2": "联系电话",
    "contactPhone1Default": "035.872.6755 (山先生)",
    "contactPhone2Default": "0968.514.882 (秀女士)",
    "contactSubjectOpt1": "志愿者报名与参与活动",
    "contactSubjectOpt2": "企业合作与ESG赞助",
    "contactSubjectOpt3": "垃圾污染黑点举报",
    "contactSubjectOpt4": "媒体采访与综合咨询",
    "contactPageFormTitle": "给协调团队发送留言",
    "contactPageThankYouTitle": "感谢您的联系！",
    "contactPageThankYouMsgPrefix": "您的留言已收到，协调团队将通过邮箱 ",
    "contactPageThankYouMsgSuffix": " 尽快与您联系。",
    "contactPageSendAnotherBtn": "发送另一条留言",
    "contactPageNameLabel": "姓名 *",
    "contactPageEmailFieldLabel": "电子邮箱 *",
    "contactPagePhoneFieldLabel": "电话号码（10位数字）",
    "contactPageSubjectLabel": "主题",
    "contactPageMessageLabel": "留言内容 *",
    "contactPageSubmitBtn": "立即发送留言"
  },
  "de": {
    "selectLanguage": "Sprache wählen",
    "topBarAnnouncement": "Die Anmeldung für Freiwillige zum World Cleanup Day 2026 ist gestartet!",
    "topBarTagline": "Let's do it! Vietnam - Gemeinsam für ein grünes, sauberes und abfallfreies Vietnam!",
    "navWhoWeAre": "Über uns",
    "navWhatWeDo": "Unsere Arbeit",
    "navOurTeam": "Unser Team",
    "navOurPartners": "Partner",
    "navProject": "Projekte",
    "navOther": "Sonstiges",
    "navMediaOnUs": "Presse",
    "navNews": "Neuigkeiten",
    "navVideos": "Videos",
    "videosPageBadge": "AKTIV WERDEN",
    "videosPageTitle": "Den Wandel im Bild festhalten",
    "videosPageSubtitle": "Sehen Sie Fernsehberichte und Dokumentationen von den Aktionen von Let's do it! Vietnam.",
    "videosPageCountSuffix": "Videos",
    "videosPageAddBtn": "Neues Video hinzufügen",
    "videosPageEmptyTitle": "Noch keine Videos vorhanden",
    "videosPageEmptyDesc": "YouTube-Link einfügen, um ein Video zu teilen",
    "navContactUs": "Kontakt",
    "navMap": "Cleanup-Karte",
    "projectWcd": "World Cleanup Day",
    "projectEnvDay": "Weltumwelttag",
    "projectGreenOcean": "Grüne Ozean-Kampagne",
    "projectYoungWildlife": "Artenschutz für Jugendliche",
    "projectWorkshop": "Gemeinschafts-Workshop",
    "viewAllProjects": "Alle Kampagnen ansehen »",
    "adminDb": "Datenbank-Admin",
    "register": "Registrieren",
    "login": "Anmelden",
    "joinVolunteer": "Freiwilliger werden",
    "profile": "Mein Profil",
    "logout": "Abmelden",
    "signUpSignIn": "Anmelden",
    "roleAdmin": "Administrator",
    "roleVolunteer": "Freiwilliger",
    "close": "Schließen",
    "privacyPolicy": "Datenschutzerklärung",
    "termsOfService": "Nutzungsbedingungen",
    "contactBubbleTitle": "Schneller Support",
    "contactBubbleSubtitle": "Wir helfen Ihnen gerne weiter",
    "contactBubbleOpenBtn": "Nachricht senden",
    "heroSlide1Badge": "WORLD CLEANUP DAY 2026 • 10 JAHRE EINSATZ FÜR DIE UMWELT",
    "heroSlide1Title": "WORLD CLEANUP DAY",
    "heroSlide1Desc": "Über 5.000 Jugendliche, Familien und Organisationen vereint für ein sauberes Vietnam.",
    "registerNowBtn": "Jetzt mitmachen",
    "exploreCampaignsBtn": "Kampagnen entdecken",
    "heroSlideTab1": "Hauptbanner",
    "heroSlideTab2": "Globale Botschaft",
    "heroSlide2Badge": "Globale Umweltinitiative",
    "heroSlide2Title1": "World Cleanup Day:",
    "heroSlide2Title2": "Global handeln, lokal wirken",
    "heroSlide2Desc": "Tausende engagierte Freiwillige schützen gemeinsam die Umwelt und trennen Müll.",
    "featureProvinces": "63 Provinzen nehmen teil",
    "featureCert": "Offizielles Zertifikat ausgestellt",
    "featureGear": "Kostenlose Schutzausrüstung",
    "joinNextEvent": "Am nächsten Event teilnehmen",
    "exploreMap": "Cleanup-Karte öffnen",
    "aboutBadge": "Über die Initiative",
    "aboutTitle": "Let's do it! Vietnam Bewegung",
    "aboutP1": "Die weltweit größte Bürgerbewegung für die Umwelt mit Millionen von Teilnehmern in über 190 Ländern.",
    "aboutP2": "Seit 2015 fördern wir nachhaltige Zero-Waste-Gewohnheiten und erfassen Müll-Hotspots.",
    "statTons": "Tonnen Müll gesammelt",
    "statTonsSub": "Sicher gesammelt und sortiert",
    "statVolunteers": "Engagierte Freiwillige",
    "statVolunteersSub": "In 63 Provinzen Vietnams",
    "statEvents": "Organisierte Cleanups",
    "statEventsSub": "Landesweit mobilisiert",
    "whoWeAreBadge": "10 Jahre Gemeinschaftsförderung",
    "whoWeAreTitlePrefix": "Wir Sind",
    "whoWeAreIntro": "Let's do it! Vietnam ist eine 2015 gegründete gemeinnützige Organisation im globalen Netzwerk von Let's Do It World.",
    "whoWeAreMissionTitle": "Unsere Mission",
    "whoWeAreMissionDesc": "Millionen von Menschen durch landesweite Cleanups und digitale Müllkarten für den Umweltschutz zu aktivieren.",
    "whoWeAreVisionTitle": "Vision 2030",
    "whoWeAreVisionDesc": "Vietnams führende Umweltbewegung und strategischer Partner des Umweltprogramms der Vereinten Nationen (UNEP) zu werden.",
    "whoWeAreValuesTitle": "Unsere Grundwerte",
    "whoWeAreVal1Title": "Aktives Handeln",
    "whoWeAreVal1Desc": "Wir reden nicht nur, sondern packen gemeinsam an und erzielen messbare Resultate.",
    "whoWeAreVal2Title": "Einheit & Offenheit",
    "whoWeAreVal2Desc": "Jeder Mensch kann unabhängig von Alter und Herkunft einen Beitrag für die Natur leisten.",
    "whoWeAreVal3Title": "Transparenz & Daten",
    "whoWeAreVal3Desc": "Präzise digitale Nachverfolgung aller gesammelten Abfallmengen und Zertifikate.",
    "whoWeAreCtaTitle": "Bereit, etwas zu verändern?",
    "whoWeAreCtaDesc": "Melden Sie sich noch heute für den World Cleanup Day 2026 an.",
    "whatWeDoBadge": "4 Handlungssäulen",
    "whatWeDoTitle": "Unsere Arbeit",
    "whatWeDoIntro": "Vom Müllsammeln am Strand bis zur Digitalisierung von Abfalldaten bieten wir ganzheitliche Lösungen.",
    "whatWeDoPillar1Title": "Landesweite Cleanup-Aktionen",
    "whatWeDoPillar1Desc": "Zehntausende Helfer säubern zeitgleich Strände, Parks und Städte.",
    "whatWeDoPillar2Title": "Umweltbildung & Workshops",
    "whatWeDoPillar2Desc": "Schulungen zur Mülltrennung an der Quelle, Ecobricks und Zero-Waste-Konzepte.",
    "whatWeDoPillar3Title": "Digitale Müll-Hotspot-Karte",
    "whatWeDoPillar3Desc": "GPS-gestützte Plattform zur Meldung und Dokumentation illegaler Müllablagerungen.",
    "whatWeDoPillar4Title": "Kreislaufwirtschaft & ESG-Partner",
    "whatWeDoPillar4Desc": "Zusammenarbeit mit Recyclingunternehmen und Beratung für nachhaltige Verpackungslösungen.",
    "whatWeDoExploreProjectsBtn": "Projekte Entdecken",
    "ourTeamBadge": "Vorstand & Koordinatoren",
    "ourTeamTitle": "Das Team von Let's do it! Vietnam",
    "ourTeamDesc": "Engagierte und leidenschaftliche Persönlichkeiten, die Umweltprojekte in ganz Vietnam leiten.",
    "ourTeamJoinTitle": "Möchtest du Regionalkoordinator werden?",
    "ourTeamJoinDesc": "Wir suchen stets engagierte junge Menschen, die unsere Standorte in neuen Provinzen leiten. Bewirb dich jetzt für die Core-Team-Rekrutierung 2026/2026!",
    "ourTeamJoinBtn": "Für das Core Team bewerben",
    "ourPartnersBadge": "Partnernetzwerk",
    "ourPartnersTitle": "Partner & Sponsoren",
    "ourPartnersDesc": "Wir danken staatlichen Institutionen, Universitäten und Unternehmen für ihre wertvolle Unterstützung.",
    "becomePartnerBtn": "Partner Werden",
    "getInvolvedTitle": "Werden Sie noch heute aktiv",
    "getInvolvedSubtitle": "Jede Tat zählt für den Schutz unseres Planeten.",
    "cardVolTitle": "Als Freiwilliger registrieren",
    "cardVolDesc": "Treten Sie Cleanups in Ihrer Nähe bei und erhalten Sie Ausrüstung und ein Zertifikat.",
    "cardVolBtn": "Als Freiwilliger anmelden",
    "cardPartnerTitle": "Unternehmenspartnerschaften",
    "cardPartnerDesc": "Bringen Sie Ihr Unternehmen mit nachhaltigen CSR- und ESG-Initiativen ein.",
    "cardPartnerBtn": "Partner werden",
    "galleryBadge": "Momente des Einsatzes",
    "galleryTitle": "Foto- & Mediengalerie",
    "gallerySubtitle": "Lächeln, Zusammenhalt und sichtbare Erfolge unserer Einsätze.",
    "galleryViewAll": "Alle Fotos ansehen",
    "mapTitle": "Nationale Cleanup-Karte",
    "mapSubtitle": "Klicken Sie auf die Karte, um einen verschmutzten Ort zu melden.",
    "streets": "Straßenkarte",
    "satellite": "Satellit",
    "terrain": "Gelände",
    "allProvinces": "Ganz Vietnam",
    "cleanupSpots": "Cleanup-Punkte",
    "pinNewLocation": "Neuer Standort markiert",
    "postTrashSpotHere": "Müllstelle hier melden",
    "viewDetails": "Details ansehen",
    "registerNow": "Jetzt anmelden",
    "footerDesc": "Globale Bürgerbewegung für ein grünes, sauberes und nachhaltiges Vietnam.",
    "quickLinks": "Direktlinks",
    "contactInfo": "Kontaktinformationen",
    "followUs": "Folgen Sie uns",
    "allRightsReserved": "Urheberrecht © Let's do it! Vietnam. Alle Rechte vorbehalten.",
    "newsPageBadge": "Nachrichten & Medienberichte",
    "newsPageTitleMedia": "Presse- & Fernsehberichte über uns",
    "newsPageTitleDefault": "Neuigkeiten & Umweltaktionen",
    "newsPageSubtitle": "Bleiben Sie informiert über aktuelle Nachrichten, TV-Reportagen und inspirierende Geschichten von unseren Einsätzen.",
    "newsPageAddArticleBtn": "Neuen Artikel einreichen",
    "newsPageAllCategoriesLabel": "Alle Artikel",
    "newsPagePendingBadge": "Ausstehende Prüfung",
    "newsPageSourceLabel": "Quelle:",
    "newsPageReadMoreBtn": "Artikel lesen",
    "newsPageBackToListBtn": "Zurück zur Übersicht",
    "newsPageSourceOriginalLabel": "Originalartikel lesen bei:",
    "newsPageDefaultSourceLabel": "Originalquelle",
    "newsCatAll": "Alle Artikel",
    "newsCatNews": "Neuigkeiten",
    "newsCatMedia": "Presseberichte",
    "newsCatPress": "Pressemitteilungen",
    "newsCatImpact": "Erfolgsgeschichten",
    "projectsBadge": "Umweltaktionen",
    "projectsTitle": "Bedeutende Umweltkampagnen & Projekte",
    "projectsSubtitle": "Wählen Sie eine Kampagne in Ihrer Region und werden Sie mit Tausenden Freiwilligen aktiv.",
    "projectsAddBtn": "Neue Cleanup-Kampagne erstellen",
    "projectsAllCategoryLabel": "Alle Kampagnen",
    "projectsDetailBtn": "Details ansehen",
    "projectsJoinBtn": "Jetzt teilnehmen",
    "fullGalleryBadge": "Foto- & Videoarchiv",
    "fullGalleryTitle": "Dokumentar- & Fotogalerie",
    "fullGallerySubtitle": "Gemeinschaft und sichtbarer Wandel bei den Einsätzen von Let's do it! Vietnam.",
    "fullGalleryAllYearsLabel": "Alle Jahre",
    "fullGalleryYearPrefix": "Jahr",
    "fullGalleryUploadBtn": "Neues Foto hochladen",
    "contactPageBadge": "Direktkontakt",
    "contactPageSubtitle": "Haben Sie Fragen, möchten Sie eine illegale Müllkippe melden oder kooperieren? Schreiben Sie uns.",
    "contactPageFindUsTitle": "Hier finden Sie uns",
    "contactPageEmailLabel": "E-MAIL-ADRESSE",
    "contactPagePhoneLabel1": "TELEFONNUMMER",
    "contactPagePhoneLabel2": "TELEFONNUMMER",
    "contactPhone1Default": "035.872.6755 (Hr. Son)",
    "contactPhone2Default": "0968.514.882 (Fr. Tu)",
    "contactSubjectOpt1": "Freiwilligen-Anmeldung & Aktionen",
    "contactSubjectOpt2": "Unternehmenspartnerschaft & ESG-Sponsoring",
    "contactSubjectOpt3": "Meldung illegaler Müllkippen",
    "contactSubjectOpt4": "Allgemeine Anfragen & Presse",
    "contactPageFormTitle": "Nachricht an das Team senden",
    "contactPageThankYouTitle": "Vielen Dank für Ihre Kontaktaufnahme!",
    "contactPageThankYouMsgPrefix": "Ihre Nachricht ist eingegangen. Unser Team wird sich per E-Mail an ",
    "contactPageThankYouMsgSuffix": " schnellstmöglich melden.",
    "contactPageSendAnotherBtn": "Weitere Nachricht senden",
    "contactPageNameLabel": "Vollständiger Name *",
    "contactPageEmailFieldLabel": "E-Mail-Adresse *",
    "contactPagePhoneFieldLabel": "Telefonnummer (10 Ziffern)",
    "contactPageSubjectLabel": "Betreff",
    "contactPageMessageLabel": "Nachricht *",
    "contactPageSubmitBtn": "Nachricht jetzt senden"
  },
  "es": {
    "selectLanguage": "Seleccionar idioma",
    "topBarAnnouncement": "¡Ya está abierta la inscripción nacional de voluntarios para el World Cleanup Day 2026!",
    "topBarTagline": "Let's do it! Vietnam - ¡Unidos por un Vietnam verde, limpio y sin residuos!",
    "navWhoWeAre": "Quiénes somos",
    "navWhatWeDo": "Qué hacemos",
    "navOurTeam": "Equipo",
    "navOurPartners": "Socios",
    "navProject": "Proyectos",
    "navOther": "Otros",
    "navMediaOnUs": "Prensa",
    "navNews": "Noticias",
    "navVideos": "Videos",
    "videosPageBadge": "ACTÚA AHORA",
    "videosPageTitle": "Capturando el cambio en cada imagen",
    "videosPageSubtitle": "Mira los reportajes de televisión y documentales de las campañas de limpieza.",
    "videosPageCountSuffix": "Videos",
    "videosPageAddBtn": "Añadir nuevo video",
    "videosPageEmptyTitle": "No hay videos aún",
    "videosPageEmptyDesc": "Pega un enlace de YouTube para compartir un video",
    "navContactUs": "Contacto",
    "navMap": "Mapa de limpieza",
    "projectWcd": "Día Mundial de la Limpieza",
    "projectEnvDay": "Día del Medio Ambiente",
    "projectGreenOcean": "Campaña Océano Verde",
    "projectYoungWildlife": "Conservación de Fauna Joven",
    "projectWorkshop": "Taller Comunitario",
    "viewAllProjects": "Ver todas las campañas »",
    "adminDb": "Admin BD",
    "register": "Registrarse",
    "login": "Iniciar sesión",
    "joinVolunteer": "Voluntariado",
    "profile": "Mi perfil",
    "logout": "Cerrar sesión",
    "signUpSignIn": "Iniciar sesión",
    "roleAdmin": "Administrador",
    "roleVolunteer": "Voluntario",
    "close": "Cerrar",
    "privacyPolicy": "Política de privacidad",
    "termsOfService": "Términos de servicio",
    "contactBubbleTitle": "Soporte rápido",
    "contactBubbleSubtitle": "Estamos aquí para ayudarte",
    "contactBubbleOpenBtn": "Enviar mensaje",
    "heroSlide1Badge": "DÍA MUNDIAL DE LA LIMPIEZA 2026 • 10 AÑOS POR EL MEDIO AMBIENTE",
    "heroSlide1Title": "DÍA MUNDIAL DE LA LIMPIEZA",
    "heroSlide1Desc": "Más de 5.000 jóvenes, familias y organizaciones unidos por un Vietnam verde y limpio.",
    "registerNowBtn": "Inscribirme ahora",
    "exploreCampaignsBtn": "Explorar campañas",
    "heroSlideTab1": "Banner principal",
    "heroSlideTab2": "Mensaje global",
    "heroSlide2Badge": "Campaña global",
    "heroSlide2Title1": "Día Mundial de la Limpieza:",
    "heroSlide2Title2": "Impacto global, acción local",
    "heroSlide2Desc": "Miles de voluntarios movilizados para la recolección, clasificación y protección ambiental.",
    "featureProvinces": "63 provincias participantes",
    "featureCert": "Certificado oficial emitido",
    "featureGear": "Equipo de protección gratis",
    "joinNextEvent": "Unirse al próximo evento",
    "exploreMap": "Ver mapa",
    "aboutBadge": "Sobre la iniciativa",
    "aboutTitle": "Movimiento Let's do it! Vietnam",
    "aboutP1": "El mayor movimiento cívico ambiental del mundo, con millones de voluntarios en más de 190 países.",
    "aboutP2": "Desde 2015 transformamos conciencias ciudadanas y promovemos el residuo cero.",
    "statTons": "Toneladas de basura recolectada",
    "statTonsSub": "Recolectadas y clasificadas de forma segura",
    "statVolunteers": "Voluntarios participantes",
    "statVolunteersSub": "En 63 provincias de Vietnam",
    "statEvents": "Eventos organizados",
    "statEventsSub": "Desplegados a nivel nacional",
    "whoWeAreBadge": "10 años de compromiso comunitario",
    "whoWeAreTitlePrefix": "Nosotros Somos",
    "whoWeAreIntro": "Fundada en 2015, Let's do it! Vietnam es una organización sin fines de lucro miembro de la red global Let's Do It World con sede en Estonia.",
    "whoWeAreMissionTitle": "Nuestra Misión",
    "whoWeAreMissionDesc": "Empoderar a millones de ciudadanos mediante limpiezas masivas y tecnología de mapeo digital de puntos críticos de basura.",
    "whoWeAreVisionTitle": "Visión 2030",
    "whoWeAreVisionDesc": "Convertirse en el movimiento ambiental ciudadano líder en Vietnam y socio estratégico del PNUMA.",
    "whoWeAreValuesTitle": "Nuestros Valores",
    "whoWeAreVal1Title": "Acción Positiva",
    "whoWeAreVal1Desc": "Trabajamos activamente en el terreno para transformar la preocupación en impacto real.",
    "whoWeAreVal2Title": "Unidad e Inclusión",
    "whoWeAreVal2Desc": "Toda persona, sin importar su edad u origen, puede aportar al bienestar del planeta.",
    "whoWeAreVal3Title": "Transparencia y Datos",
    "whoWeAreVal3Desc": "Seguimiento digital riguroso de toneladas recolectadas y certificados emitidos.",
    "whoWeAreCtaTitle": "¿Listo para marcar la diferencia?",
    "whoWeAreCtaDesc": "Únete a miles de voluntarios e inscríbete hoy para el World Cleanup Day 2026.",
    "whatWeDoBadge": "4 Pilares de Acción",
    "whatWeDoTitle": "Qué Hacemos",
    "whatWeDoIntro": "Desde limpiezas costeras hasta digitalización de datos sobre desechos, creamos soluciones sostenibles.",
    "whatWeDoPillar1Title": "Campañas Nacionales de Limpieza",
    "whatWeDoPillar1Desc": "Movilización masiva de decenas de miles de voluntarios en el Día Mundial de la Limpieza.",
    "whatWeDoPillar2Title": "Educación Ecológica y Talleres",
    "whatWeDoPillar2Desc": "Capacitación en separación en origen, ecoladrillos y estilo de vida Residuo Cero.",
    "whatWeDoPillar3Title": "Mapeo Digital de Puntos de Basura",
    "whatWeDoPillar3Desc": "Tecnología GPS para que la comunidad reporte y rastree vertederos ilegales.",
    "whatWeDoPillar4Title": "Economía Circular y Alianzas ESG",
    "whatWeDoPillar4Desc": "Alianzas con recicladores y asesoría a empresas en Responsabilidad Extendida del Productor.",
    "whatWeDoExploreProjectsBtn": "Explorar Proyectos",
    "ourTeamBadge": "Directiva y Coordinadores",
    "ourTeamTitle": "El Equipo de Let's do it! Vietnam",
    "ourTeamDesc": "Líderes apasionados y dedicados que impulsan iniciativas ambientales en todo Vietnam.",
    "ourTeamJoinTitle": "¿Quieres ser coordinador regional?",
    "ourTeamJoinDesc": "Siempre buscamos jóvenes apasionados para liderar nuestros puntos de enlace en nuevas provincias. ¡Únete a la convocatoria del Core Team 2026/2026 hoy mismo!",
    "ourTeamJoinBtn": "Postularse al Core Team",
    "ourPartnersBadge": "Red de Aliados",
    "ourPartnersTitle": "Socios y Patrocinadores",
    "ourPartnersDesc": "Agradecemos el valioso respaldo de instituciones gubernamentales, universidades y empresas líderes.",
    "becomePartnerBtn": "Ser Aliado",
    "getInvolvedTitle": "Únete a la acción hoy",
    "getInvolvedSubtitle": "Cada acción cuenta para proteger nuestro planeta.",
    "cardVolTitle": "Regístrate como voluntario",
    "cardVolDesc": "Únete a los puntos de limpieza cercanos y recibe tu equipamiento y certificado oficial.",
    "cardVolBtn": "Inscribirse como voluntario",
    "cardPartnerTitle": "Alianzas corporativas",
    "cardPartnerDesc": "Involucre a su empresa en programas de responsabilidad social y sostenibilidad.",
    "cardPartnerBtn": "Ser socio aliado",
    "galleryBadge": "Momentos de acción",
    "galleryTitle": "Galería de fotos y medios",
    "gallerySubtitle": "Sonrisas y compromiso en cada una de nuestras jornadas ambientales.",
    "galleryViewAll": "Ver todas las fotos",
    "mapTitle": "Mapa nacional de puntos de limpieza",
    "mapSubtitle": "Haga clic en el mapa para fijar una ubicación y reportar un punto de recolección de basura.",
    "streets": "Calles",
    "satellite": "Satélite",
    "terrain": "Relieve",
    "allProvinces": "Todo Vietnam",
    "cleanupSpots": "Puntos de limpieza",
    "pinNewLocation": "Nueva ubicación fijada",
    "postTrashSpotHere": "Publicar punto aquí",
    "viewDetails": "Ver detalles",
    "registerNow": "Inscribirse ahora",
    "footerDesc": "Movimiento cívico global por un Vietnam verde, limpio y sostenible.",
    "quickLinks": "Enlaces rápidos",
    "contactInfo": "Información de contacto",
    "followUs": "Síguenos",
    "allRightsReserved": "Derechos de autor © Let's do it! Vietnam. Todos los derechos reservados.",
    "newsPageBadge": "Noticias y Medios",
    "newsPageTitleMedia": "Cobertura de Prensa y TV sobre Nosotros",
    "newsPageTitleDefault": "Noticias y Actividades Ambientales",
    "newsPageSubtitle": "Manténgase informado con las últimas noticias, reportajes de TV y testimonios inspiradores de nuestras campañas.",
    "newsPageAddArticleBtn": "Publicar un Artículo / Noticia",
    "newsPageAllCategoriesLabel": "Todos los Artículos",
    "newsPagePendingBadge": "Pendiente de Revisión",
    "newsPageSourceLabel": "Fuente:",
    "newsPageReadMoreBtn": "Leer Artículo",
    "newsPageBackToListBtn": "Volver a la Lista",
    "newsPageSourceOriginalLabel": "Ver artículo original en:",
    "newsPageDefaultSourceLabel": "Fuente Original",
    "newsCatAll": "Todos los Artículos",
    "newsCatNews": "Noticias",
    "newsCatMedia": "Prensa y Medios",
    "newsCatPress": "Comunicados de prensa",
    "newsCatImpact": "Historias de impacto",
    "projectsBadge": "Acción Ambiental",
    "projectsTitle": "Campañas y Proyectos Ambientales Clave",
    "projectsSubtitle": "Seleccione una campaña en su localidad y actúe hoy con miles de voluntarios.",
    "projectsAddBtn": "Crear Nueva Campaña de Limpieza",
    "projectsAllCategoryLabel": "Todas las Campañas",
    "projectsDetailBtn": "Ver Detalles",
    "projectsJoinBtn": "Inscribirse en la Campaña",
    "fullGalleryBadge": "Archivo de Fotos y Videos",
    "fullGalleryTitle": "Galería Documental y Fotográfica",
    "fullGallerySubtitle": "Sonrisas y transformación en cada campaña de Let's do it! Vietnam.",
    "fullGalleryAllYearsLabel": "Todos los Años",
    "fullGalleryYearPrefix": "Año",
    "fullGalleryUploadBtn": "Subir Nueva Foto",
    "contactPageBadge": "Contacto Directo",
    "contactPageSubtitle": "¿Tiene preguntas, desea reportar un basurero o colaborar en una campaña? Envíenos un mensaje.",
    "contactPageFindUsTitle": "Puedes encontrarnos en",
    "contactPageEmailLabel": "CORREO ELECTRÓNICO",
    "contactPagePhoneLabel1": "NÚMERO DE TELÉFONO",
    "contactPagePhoneLabel2": "NÚMERO DE TELÉFONO",
    "contactPhone1Default": "035.872.6755 (Sr. Son)",
    "contactPhone2Default": "0968.514.882 (Sra. Tu)",
    "contactSubjectOpt1": "Registro de voluntarios y campañas",
    "contactSubjectOpt2": "Alianzas corporativas y patrocinio ESG",
    "contactSubjectOpt3": "Reportar basurero ilegal",
    "contactSubjectOpt4": "Consultas generales y prensa",
    "contactPageFormTitle": "Enviar Mensaje al Equipo",
    "contactPageThankYouTitle": "¡Gracias por Contactarnos!",
    "contactPageThankYouMsgPrefix": "Su mensaje ha sido recibido. Responderemos a su correo ",
    "contactPageThankYouMsgSuffix": " lo antes posible.",
    "contactPageSendAnotherBtn": "Enviar Otro Mensaje",
    "contactPageNameLabel": "Nombre Completo *",
    "contactPageEmailFieldLabel": "Correo Electrónico *",
    "contactPagePhoneFieldLabel": "Número de Teléfono (10 dígitos)",
    "contactPageSubjectLabel": "Asunto",
    "contactPageMessageLabel": "Mensaje *",
    "contactPageSubmitBtn": "Enviar Mensaje Ahora"
  }
};

interface LanguageContextType {
  language: Language;
  t: typeof translations['vi'];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Locked to English site-wide — the language switcher UI was removed per
// request ("bỏ ngôn ngữ đi chuyển hết sang tiếng anh, không có ngôn ngữ khác
// nữa"). `language` is kept as a real piece of context state (rather than
// deleting it and the `Language` union) since dozens of components still do
// `language === 'vi' ? ... : ...` for their own copy — those checks simply
// always take the non-Vietnamese branch now. Also means useAutoTranslate's
// early-return for 'vi' never fires, so admin-entered content (which is
// mostly typed in Vietnamese) now gets auto-translated to English everywhere.
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const language: Language = 'en';
  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};


